### ISSUE TITLE
example clickToClose not working

### ISSUE THREAD

**Issue by dodoshanti** [flauc/angular2-notifications#10]
Hi

I cloned the project and ran the example locally. I can create the notifications but clicking on them doesn't close it.

Am I missing something?

Thanks

**Comment by flauc** [comment]
Hey, 

Could you provide a code sample please?

**Comment by flauc** [comment]
Oh you cloned the repo, sorry. Your right it's behaving funny to me as well. I've been making some changes and i might have broken something. I'll take a look right away.

**Comment by flauc** [comment]
Hi again, 

I've fixed the issue. If you clone the repo now every thing should be working just fine.

**Comment by dodoshanti** [comment]
Respect! It works!
