### ISSUE TITLE
Errors in library

### ISSUE THREAD

**Issue by Nikhil-Pahwa** [flauc/angular2-notifications#102]
I am getting following errors 

notification.component.ts
- Line no. 251 `this[a] = this.item.override[a];`  and error is `[ts] Index signature of object type implicitly has an 'any' type.`

simple-notifications.component
- Line no. 184 `this[a] = this.item.options[a];`  and error is `[ts] Index signature of object type implicitly has an 'any' type.`

Due to which i am not able run Karma. Please help me in this regard. Thanks in advance.

**Comment by primero** [comment]
I've added PR which fixes issue for me: https://github.com/flauc/angular2-notifications/pull/110
