### ISSUE TITLE
Failure to load in IE11

### ISSUE THREAD

**Issue by lohengrin332** [flauc/angular2-notifications#103]
In IE11 with this module included I receive the following error in the browser, and my application does not load.  If I remove the module the application loads.

Error:
```
(SystemJS) Syntax error
    SyntaxError: Syntax error
        at Anonymous function (eval code:2:1)
        at Anonymous function (eval code:1:31)
        at eval code (eval code:1:2)
    Evaluating <host url>/angular2-notifications/src/simple-notifications.module.js
    Evaluating <host url>/angular2-notifications/src/components.js
    Evaluating <host url>/app/app.module.js
    Evaluating <host url>/app/main.js
    Error loading <host url>/app/main.js
```

My package.json:
```javascript
{
  "name": "MyApp",
  "main": "server/server.js",
  "scripts": {
    "start": "node server/server",
    "postinstall": "cd client && typings install",
    "tsc": "tsc"
  },
  "dependencies": {
    "@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/router": "~3.1.2",
    "@angular/upgrade": "~2.1.2",
    "angular2-notifications": "^0.4.46",
    "body-parser": "1.15.2",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "express": "~4.14.0",
    "fs": "0.0.1-security",
    "joi": "^9.0.0",
    "method-override": "2.3.6",
    "multer": "^1.2.0",
    "node-uuid": "^1.4.7",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "^0.19.40",
    "winston": "^2.2.0",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "del": "^2.1.0",
    "gulp": "3.9.1",
    "gulp-mocha": "^2.2.0",
    "gulp-nodemon": "2.1.0",
    "gulp-typings": "^2.0.3",
    "mocha": "^2.5.3",
    "mocha-jenkins-reporter": "^0.2.3",
    "run-sequence": "^1.2.2",
    "typescript": "^2.0.6",
    "typings": "^1.5.0"
  }
}
```

My index.html:
```html
<!doctype html>
<html lang="en">
  <head>
    <base href='/' />

    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <link rel='stylesheet' href='lib/bootstrap/dist/css/bootstrap.min.css'>
    <!-- <link rel='stylesheet' href='style.css'> -->

    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src='lib/core-js/client/shim.min.js'></script>

    <script src='lib/zone.js/dist/zone.js'></script>
    <script src='lib/reflect-metadata/Reflect.js'></script>
    <script src='lib/systemjs/dist/system.src.js'></script>

    <!-- 2. Configure SystemJS -->
    <script src='systemjs.config.js'></script>
    <script>
        System.import('app').catch(function(err) { console.error(err); });
    </script>

    <title>MyApp</title>
  </head>

  <!-- 3. Display the application -->
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```

My systemjs.config.js:
```javascript
(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'lib/@angular',
    'rxjs':                       'lib/rxjs',
    'angular2-notifications':     'lib/angular2-notifications'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-notifications':     { main: 'components.js', defaultExtension: 'js' }
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  };
  System.config(config);
})(this);
```

My app.module.ts:
```typescript
import { NgModule      } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule   } from '@angular/forms';
import { HttpModule    } from '@angular/http';

import './rxjs-operators';

import { SimpleNotificationsModule } from 'angular2-notifications';

import { AppComponent  }  from './app.component';
import { routing } from './app.routing';

import { NotFoundComponent } from './not-found.component';

@NgModule({
    imports:      [ BrowserModule, FormsModule, HttpModule, SimpleNotificationsModule, routing ],
    declarations: [ AppComponent, NotFoundComponent ],
    bootstrap:    [ AppComponent ]
})

export class AppModule { }
```

I'm using tsc to transpile my code to es5, and using systemjs to load it into the browser.  Please let me know if you need any additional information to reproduce this issue, or if you have a suggested workaround.  Thank you!

**Comment by flauc** [comment]
Hi @lohengrin332,

Thank you for pointing this out 👍 
Sadly i have very little experience with IE errors. I'll try to work on it, hopefully someone has some experience?

**Comment by lohengrin332** [comment]
@flauc,

I've been working on this in the interim.  I believe the issue is that IE11 doesn't support ES6/ES2015, but you have ES6 directives in some of the JS files that are bundled with the npm package.  See the class declaration on line 8 in src/simple-notifications.module.js as installed by npm.  I think that if you change the build target in tsconfig.aot.json from `es2015` to `es5` and correct the resulting errors, it might correct this issue, but I've been unable to get it to compile on my own machines.

I've also been trying to use AOT compilation.  I get it working to a point after fiddling with the way your libraries are included (similar issues as with #82), but for some reason the `$e` in [src/notification.component.ts](https://github.com/flauc/angular2-notifications/blob/master/src/notification.component.ts#L240) gets translated during compilation to `this.context.$e` in the generated JS file, which of course errors because the notification component doesn't have a `$e` attribute.  I fixed this by changing `$e` to `$event` in that function and it seems to work, translating into a local variable instead of trying to use a class attribute.  I've no idea _why_ this works, but it seems to.

Thanks for this plugin; the notifications look great and it's very flexible.

**Comment by lohengrin332** [comment]
@flauc: [this commit](https://github.com/flauc/angular2-notifications/commit/fe68c221cd54d1727ebfcea1585917e36f2cf6c4) appears to address my AOT issue.  Once that is deployed to NPM I should be good to go, and we'll probably be able to resolve this issue along with #82.  Thanks.

**Comment by flauc** [comment]
Hey @lohengrin332, 

This is on npm now version [0.4.47](https://www.npmjs.com/package/angular2-notifications)

**Comment by flauc** [comment]
I'm not entirely sure it handles both issues, but do let me know if it does. Thanks 👍

**Comment by GopiAnnan** [comment]
@flauc .. I have tried with 0.4.47, in IE still its not working. Facing the same issue.

"(SystemJS) Syntax error
	SyntaxError: Syntax error
	   at Anonymous function (eval code:2:1)
	   at Anonymous function (eval code:1:31)
	   at eval code (eval code:1:2)
	Evaluating http://localhost:3000/node_modules/angular2-notifications/src/simple-notifications.module.js
	Evaluating http://localhost:3000/node_modules/angular2-notifications/components.js

**Comment by lohengrin332** [comment]
@flauc,

I've confirmed that it works using AOT. Thanks.
