### ISSUE TITLE
Can't make it work outside of <router-outlet/>

### ISSUE THREAD

**Issue by guzmo** [flauc/angular2-notifications#105]
I've tried adding 

`<simple-notifications></simple-notifications>`

inside components and then it works, but when I add it to my app.html outside of router-outlet I can't get it to show.

I'm using a CoreModule and SharedModule and added it to CoreModule inside exports: [] and only import CoreModule to my AppModule.

**Comment by JeremiasIsnardy** [comment]
Similar problem on my side.
By using a router I load some modules for my content area, the components of this modules are not able to trigger the notification. By accessing a SharedModule the SimpleNotificationsModule gets exported to each sub module.
A workaround: defining  <simple-notifications></simple-notifications> for each module, but this gets quite annoying when you want to manage global notifcations options (and its also annoying do define it each time separately)

**Comment by flauc** [comment]
Hi guys, 

I'm not sure i follow. If you import and export the `SimpleNotificationsModule` in your `SharedModule` then in you `app.component.ts` you add the `<simple-notifications></simple-notifications>` everything should work. 

Here is an example: 

app.component.ts
```
@Component({
    selector: 'app',
    template: `
        <router-outlet></router-outlet>
        <simple-notifications [options]="notificationOptions"></simple-notifications>
    `
})

export class AppComponent {
    notificationOptions: any = {
        timeOut: 5000,
        lastOnBottom: true,
        showProgressBar: true,
        pauseOnHover: true,
        clickToClose: true
    };
}
```

shared.module.ts
```
@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        // External
        SimpleNotificationsModule
    ],
    exports: [
        CommonModule,
        FormsModule,
        // External
        SimpleNotificationsModule
    ]
})
export class SharedModule {}
```

I can then use the `NotificationsService` in any module that imports the `SharedModule`

**Comment by bibsi0212** [comment]
Having the same problem here - is there any news on this topic?

**Comment by flauc** [comment]
Have you tried the above approach?

**Comment by bibsi0212** [comment]
Yes I have tried it the same way as you described. The notification template is in my main-component and the success call is made in another sub-component - i get no errors but the notification is not showing. If I move the template in the same component where I make the success call it works.

**Comment by cirellamhcs** [comment]
Hi,

I got the same setup as described above and have the same issue. The notification will not be shown when getting triggered in any module.

**Comment by jqyoong** [comment]
Hi,

I met the same problem, my thought is when we put our the notification component at our parent component (app.component.ts), the component is initiated together with the service in the angular2-notification module, which our project has not constructed the service yet. That means the service that `simple-notifications.component.ts`  subscribing is the service constructed together with the `simple-notification.module.ts` but not the service in `app.module.ts`, which mean the service `simple-notifications.component.ts` is subscribing is not the same service constructed in the `app.module.ts`. But those are my assumptions, feel free to correct me if I'm wrong.

Solution,
`In simple-notifications.module.ts` , take out the `notifications.service.ts`  import and providers, then import the `notifications.service.ts` in your `app.module.ts` and put in the providers as well. Now you can call the service across your web apps.
