### ISSUE TITLE
[Docs] Wrong docs for overriding global options

### ISSUE THREAD

**Issue by richardsengers** [flauc/angular2-notifications#107]
HI,

Thanks for the beautifull Notifications!
I've noticed an error in de docs about the Toaster.

The docs state that to override the options you need to add an object to the success method. Or at least...I thought it would be an object

```
this._notificationsService.success(
    title: 'example',
    content:'example',
    override: {
        timeOut: 5000,
        showProgressBar: true,
        pauseOnHover: false,
        clickToClose: false,
        maxLength: 10
    }
)
```

I hought the brackets were missing so this would be the right way to implement it:

```
this._notificationsService.success({
    title: 'example',
    content:'example',
    override: {
        timeOut: 5000,
        showProgressBar: true,
        pauseOnHover: false,
        clickToClose: false,
        maxLength: 10
    }
})
```

This is however incorrect and throughs a weird error: "Supplied parameters do not match any signature of call target.".

It took me some time to find out what I did wrong :-) So hopefully you can adjust the docs a little bit

The correct way:
```
this._notificationsService.success('example','example', override: {
        timeOut: 5000,
        showProgressBar: true,
        pauseOnHover: false,
        clickToClose: false,
        maxLength: 10
    })
```

**Comment by flauc** [comment]
You're right my example makes no sense. Thank you for pointing this out 👍 
will fix shortly.

**Comment by flauc** [comment]
Fixed, thanks again 👍
