### ISSUE TITLE
Fix TypeScript typing

### ISSUE THREAD

**Issue by Toktik** [flauc/angular2-notifications#11]
After renaming `NotificationsService::removeAll()` to `NotificationsService::remove()` typings should be updated accordingly in `angular2-notifications/notifications.service.d.ts`.

Btw how do you publish this project to npm? I don't see prepublish scripts in package.json

**Comment by flauc** [comment]
Thanks for the heads up. 

I'm not really using any build task, it's a really lightweight library and all i do is transpile the ts files in to the lib directory before publishing.
