### ISSUE TITLE
Source code breaks compile

### ISSUE THREAD

**Issue by xealot** [flauc/angular2-notifications#111]
This might be related to #78 

Shipping the source with the project and referencing breaks the compile.

Since the TS compiler finds TS sources in node_modules it moves the project's `rootDir` and then creates bad output (directories are moved around to accommodate node_modules).

Alternatively, if you manually set `rootDir` in a project, you get a lot of the following types of error.

```
error TS6059: File './node_modules/angular2-notifications/src/push-notification.type.ts' is not under 'rootDir' './src'. 'rootDir' is expected to contain all source files.
```

**Comment by xealot** [comment]
Also #99

**Comment by flauc** [comment]
closing in favor of #162
