### ISSUE TITLE
Error after update "0.3.6" to "^0.4.46"

### ISSUE THREAD

**Issue by rafaelcb21** [flauc/angular2-notifications#113]
Hello sir.

After updating from version `"0.3.6"` to `"^0.4.46"` the following error appears:

`error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/icons.ts' is not under 'rootDir' 'C:/Users/R/Desktop/mean/myApp/./ap
'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/max.pipe.ts' is not under 'rootDir' 'C:/Users/R/Desktop/mean/myApp/.
'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/notification-event.type.ts' is not under 'rootDir' 'C:/Users/R/Desktop/m
myApp/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/notification.component.ts' is not under 'rootDir' 'C:/Users/R/Desktop/me
cbanespa/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/notification.type.ts' is not under 'rootDir' 'C:/Users/R/Desktop/mean/ec
spa/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/notifications.service.ts' is not under 'rootDir' 'C:/Users/R/Desktop/mea
banespa/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/options.type.ts' is not under 'rootDir' 'C:/Users/R/Desktop/mean/ecbanes
/app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/push-notification.type.ts' is not under 'rootDir' 'C:/Users/R/Desktop/me
cbanespa/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/push-notifications.module.ts' is not under 'rootDir' 'C:/Users/R/Desktop
n/myApp/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/push-notifications.service.ts' is not under 'rootDir' 'C:/Users/R/Deskto
an/myApp/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/simple-notifications.component.ts' is not under 'rootDir' 'C:/Users/R/De
p/mean/myApp/./app'. 'rootDir' is expected to contain all source files.
error TS6059: File 'C:/Users/R/Desktop/mean/myApp/node_modules/angular2-notifications/src/simple-notifications.module.ts' is not under 'rootDir' 'C:/Users/R/Deskt
ean/myApp/./app'. 'rootDir' is expected to contain all source files.
[22:47:32] TypeScript: 12 options errors`

**gulpfile.js**

    var gulp = require('gulp');
    var gulpTypescript = require('gulp-typescript');
    var gulpSourcemaps = require('gulp-sourcemaps');

    var del = require('del');

    var appDev = 'app/';
    var appProd = 'public/js/app/';
    var vendor = 'public/js/vendor/';

    var tsconfig = gulpTypescript.createProject('tsconfig.json', {
        typescript: require('typescript')
    });

    gulp.task('build-ts', function () {
        var tsResult = tsconfig.src()
            .pipe(tsconfig());
        return tsResult.js.pipe(gulp.dest(appProd));
    });

    gulp.task('build-copy', function() {
    return gulp.src([appDev + '**/*.html', appDev + '**/*.css'])
        .pipe(gulp.dest(appProd));
    });

    gulp.task('clean', function() {
    del(appProd + '**/*');
    });

    gulp.task('vendor', function() {
        //@angular
        gulp.src('node_modules/@angular/**')
            .pipe(gulp.dest(vendor + '/@angular/'));

        //es6-shim
        gulp.src('node_modules/es6-shim/**')
            .pipe(gulp.dest(vendor + '/es6-shim/'));

        //reflect metadata
        gulp.src('node_modules/reflect-metadata/**')
            .pipe(gulp.dest(vendor + '/reflect-metadata/'));

        //rxjs
        gulp.src('node_modules/rxjs/**')
            .pipe(gulp.dest(vendor + '/rxjs/'));

        //systemjs
        gulp.src('node_modules/systemjs/**')
            .pipe(gulp.dest(vendor + '/systemjs/'));

        //angular2-notifications
        gulp.src('node_modules/angular2-notifications/**')
            .pipe(gulp.dest(vendor + '/angular2-notifications/'));

        //zonejs
        return gulp.src('node_modules/zone.js/**')
            .pipe(gulp.dest(vendor + '/zone.js/'));
    });

    gulp.task('watch', function() {
    gulp.watch(appDev + '**/*.ts', ['build-ts']);
    gulp.watch(appDev + '**/*.{html,css}', ['build-copy']);
    });

    gulp.task('default', ['watch', 'build-ts', 'build-copy', 'vendor']);
    gulp.task('build', ['build-ts', 'build-copy', 'vendor']);
`
**tsconfig.json**

    {
        "compilerOptions": {
            "target": "es5",
            "module": "commonjs",
            "moduleResolution": "node",
            "sourceMap": true,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "removeComments": false,
            "noImplicitAny": false,
            "outDir": "../public/js/app"
        },
        "files":[
            "./app/*"
        ],
        "exclude":[
            "node-modules"
        ]
    }

**systemjs.config.js**

    (function (global) {
        var map = {
            'app': 'js/app',
            '@angular/core': 'js/vendor/@angular/core',
            '@angular/common': 'js/vendor/@angular/common',
            '@angular/compiler': 'js/vendor/@angular/compiler',
            '@angular/platform-browser': 'js/vendor/@angular/platform-browser',
            '@angular/platform-browser-dynamic': 'js/vendor/@angular/platform-browser-dynamic',
            '@angular/http': 'js/vendor/@angular/http',
            '@angular/router': 'js/vendor/@angular/router',
            '@angular/forms': 'js/vendor/@angular/forms',
            'rxjs': 'js/vendor/rxjs',
            'angular2-notifications': 'js/vendor/angular2-notifications',
            },

            packages = {
                'app': { main: 'boot.js', defaultExtension: 'js' },
                'rxjs': { defaultExtension: 'js' },
                'angular2-notifications': { main: 'components.js', defaultExtension: 'js' },
                '@angular/core': { main: 'bundles/core.umd.js', defaultExtension: 'js' },
                '@angular/common': { main: 'bundles/common.umd.js', defaultExtension: 'js' },
                '@angular/compiler': { main: 'bundles/compiler.umd.js', defaultExtension: 'js' },
                '@angular/platform-browser': { main: 'bundles/platform-browser.umd.js', defaultExtension: 'js' },
                '@angular/platform-browser-dynamic': { main: 'bundles/platform-browser-dynamic.umd.js', defaultExtension: 'js' },
                '@angular/http': { main: 'bundles/http.umd.js', defaultExtension: 'js' },
                '@angular/router': { main: 'bundles/router.umd.js', defaultExtension: 'js' },
                '@angular/forms': { main: 'bundles/forms.umd.js', defaultExtension: 'js' },
            };
        System.config({map: map, packages: packages});

    })(this);

Any solutions?

**Comment by flauc** [comment]
Hi @rafaelcb21

I know this took an age, but should be resolved with latest update.
