### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by kamcik** [flauc/angular2-notifications#114]
Hello,

I have problem with adding notifications to my project. While loading page, I get an error:

> zone.js:388 Unhandled Promise rejection: Template parse errors:
> Can't bind to 'options' since it isn't a known property of 'simple-notifications'.
> 1. If 'simple-notifications' is an Angular component and it has 'options' input, then verify that it is part of this module.
> 2. If 'simple-notifications' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
>  ("
> <body>
> 
>   <simple-notifications [ERROR ->][options]="options"></simple-notifications>
> 
>     <div id="wrapper">
> "): Home@17:24
> 'simple-notifications' is not a known element:
> 1. If 'simple-notifications' is an Angular component, then verify that it is part of this module.
> 2. If 'simple-notifications' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
> <body>
> 
>   [ERROR ->]<simple-notifications [options]="options"></simple-notifications>
> 
> I know, that there's an issue with the same problem (#86) but It doesn't give me any clue.

I will be grateful for any clues.

**Comment by UnCacatoes** [comment]
I got the same issue when I updated angular from version 2.0.1 to 2.1.2.
Try switching your angular2-notifications to version 0.4.3, it's working with the latest build of angular.
Waiting for a fix.

**Comment by kamcik** [comment]
Thank's! It's working.

**Comment by miraj92** [comment]
Not working with latest version as well. Seems as a blocker as the older version needs beta 12 version while angular uses 5.0.3 stable version.

**Comment by flauc** [comment]
I just updated to ng 4, I think this issue should be resolved now, let me know if you are still getting it though.

**Comment by gauravarora** [comment]
I'm on angular 4.2.2 and I still see this error.

**Comment by pnowy** [comment]
The same for me with angular 4.2.6 and 0.7.7

**Comment by katafractari** [comment]
Same for me with Angular 4.3.1 and 0.7.8

**Comment by dyhaz** [comment]
I have the same issue
Here is my package.json file:
> {
  "name": "`@`coreui/angular",
  "version": "1.0.5",
  "description": "Open Source Bootstrap Admin Template",
  "author": "Łukasz Holeczek",
  "homepage": "http://coreui.io",
  "copyright": "Copyright 2017 creativeLabs Łukasz Holeczek",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "`@`angular/animations": "~4.4.4",
    "`@`angular/cdk": "^5.0.0-rc0",
    "`@`angular/common": "~4.4.4",
    "`@`angular/compiler": "~4.4.4",
    "`@`angular/core": "~4.4.4",
    "`@`angular/forms": "~4.4.4",
    "`@`angular/http": "~4.4.4",
    "`@`angular/material": "^5.0.0-rc0",
    "`@`angular/platform-browser": "~4.4.4",
    "`@`angular/platform-browser-dynamic": "~4.4.4",
    "`@`angular/platform-server": "~4.4.4",
    "`@`angular/router": "~4.4.4",
    "angular2-notifications": "^0.9.6",
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "2.7.1",
    "core-js": "2.5.1",
    "font-awesome": "^4.7.0",
    "moment": "2.19.1",
    "ng2-charts": "1.6.0",
    "ngx-bootstrap": "1.9.3",
    "rxjs": "5.5.2",
    "simple-line-icons": "^2.4.1",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "`@`angular/cli": "1.2.0",
    "`@`angular/compiler-cli": "^4.0.0",
    "`@`angular/language-service": "^4.0.0",
    "`@`types/jasmine": "~2.5.53",
    "`@`types/jasminewd2": "~2.0.2",
    "`@`types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  },
  "engines": {
    "node": ">= 6.9.0",
    "npm": ">= 3.0.0"
  }
}
