### ISSUE TITLE
JS exceptions after opening notifications

### ISSUE THREAD

**Issue by pavlokitdev** [flauc/angular2-notifications#117]
After triggering .open() notification popup appears on the page
but I have few exceptions in console, also popup is broken/not clickable in this moment

http://take.ms/xWMzW

I'm trying to use this lib with Meteor and Angular 2.1.2
Thanks for any help!

**Comment by flauc** [comment]
Hi @pavlokitdev,

Sorry for taking so long to respond.

I think that's the MaxPipe on the content, anyway you shouldn't get this error on the newest version.
