### ISSUE TITLE
(feature): Remove rxjs dependency from package.json

### ISSUE THREAD

**Issue by nick1247** [flauc/angular2-notifications#118]
Remove rxjs dependency from package.json for preventing conflicts, @angular/core already [has it](https://github.com/angular/angular/blob/master/modules/%40angular/core/package.json#L11)

**Comment by pverdu** [comment]
Would be nice. We're getting an ``` UNMET PEER DEPENDENCY rxjs@5.0.0-rc.4``` at the moment when upgrading to Angular 2.3

**Comment by flauc** [comment]
Hey guys, I've just done this. Let me know if it fixes the problem for you. I'm not getting this error so I can't check on my own. 

Thanks 👍

**Comment by nick1247** [comment]
Yep, it fexes

**Comment by flauc** [comment]
Thank you
