### ISSUE TITLE
Add support to have other options for position property

### ISSUE THREAD

**Issue by bhaskerchari** [flauc/angular2-notifications#120]
Hi @flauc,

First of all thanks for the awesome lightweight notifications library I feel it is really cool also having support for PushNotifications as well. 

I think it would be better if we could also add support for having other options for position property such as to have [top, middle] and [bottom, middle] and center (for displaying the notification in the center of the browser window vertically and horizontally center).

This is a suggestion in a way to draw more user attention to the notification in a way like most of the app's may have a single notification at a time though there could be usecases where we endup showing multiple notifications but most common thing is to have a single notification so it would make sense to position the notification in the center of the browser window.

Please share your thoughts on this.

Thanks in advance,
Bhasker

**Comment by flauc** [comment]
HI @bhaskerchari,

Yes I totally agree. So following the current convention we have in place. It should look something like this: 

- [center, center] 
- [center, top]
- [top, center]

I'm completely swamped with other projects at the moment, but I'll look in to adding this as soon as possible. 

If you want feel free to send a PM.

Great idea, thanks 👍

**Comment by bhaskerchari** [comment]
@flauc ,

Sure the conventions seems just fine to keep it consistent. Yeah you can add it once you are free with other stuff.

One more enhancement which might come handy may not be related to the current post but it would be better if we could add a callback support as when a notification is destroyed or closed when we show a notification using NotificationsService.

I believe we do have a way right now by registering for onCreate and onDestroy events but this is at the central place which gets called for all notifications.

I am not sure if there is a way if i would be able to subscribe to an event or a callback on an individual notification shown.

Thanks again,
Bhasker

**Comment by bhaskerchari** [comment]
@flauc ,

Any update on this? Did you get a chance to look into this?

Thanks,
Bhasker

**Comment by atapas** [comment]
+1 for this one.

**Comment by jeremyputeaux** [comment]
+1! Don't forget [bottom, center].

**Comment by ShinDarth** [comment]
+1 for this feature request. It would be very nice to have it! `[bottom, center]`

**Comment by Spawnrad** [comment]
+1

**Comment by laertispappas** [comment]
@flauc Can I give it a try and implement this?

**Comment by ShinDarth** [comment]
@laertispappas it would be great if you can do it

**Comment by bhaskerchari** [comment]
@flauc ,

I believe you can close this issue now since the library now supports various options mentioned in my post.

Thanks,
Bhasker

**Comment by flauc** [comment]
@bhaskerchari awesome thanks
