### ISSUE TITLE
Error with Karma

### ISSUE THREAD

**Issue by tctc91** [flauc/angular2-notifications#13]
In our main systemjs config we're getting an "export undefined" error.

System.config({
  baseURL: '/base/',
  defaultJSExtensions: true,
  paths: {
    'angular2/*':       'node_modules/angular2/*.js',
    'rxjs/*':           'node_modules/rxjs/*.js',
    'moment':           'node_modules/moment/moment.js',
    'braintree':        'node_modules/braintree-web/dist/braintree.js',
    'ng2-bootstrap/*':  'node_modules/ng2-bootstrap/*.js',
    'angulartics2/*':   'node_modules/angulartics2/*.js',
  },
  map: {
    'angular2-notifications/*':   'node_modules/angular2-notifications'
  }
});

When we don't include this map property, it works. However - Karma stops working and gives an error:

04 04 2016 17:24:00.019:WARN [web-server]: 404: /base/angular2-notifications/components.js

Any help much appreciated!

**Comment by flauc** [comment]
I'm not quite sure what the problem is. It's kind of hard to figure it out with just the error messages.

What is the '*' for at the end of 'angular2-notifications/'?  Did you try mapping it with out the asterisk?
