### ISSUE TITLE
OnPush

### ISSUE THREAD

**Issue by Sn3b** [flauc/angular2-notifications#135]
I'm using OnPush strategy and for some reason the notification opens but stays, unless I scroll the progress bar doesn't do anything. Any idea how to use it? I've tried using changeDetectorRef.detectChanges() and changeDetectorRef.markForCheck but no success :(

**Comment by flauc** [comment]
Huh I think I need to switch to OnPush in the library for it to work. 
Sorry about that. I'll try to update this by tomorrow. 

Thanks for pointing it out 👍

**Comment by Sn3b** [comment]
That'd be awzsome :)

**Comment by Sn3b** [comment]
No time so far I guess? Do you think you might be able to implement that any time soon?

**Comment by flauc** [comment]
Meh I'm sorry I was completely tied up so far. I'll do my best to get this updated as soon as possible.

**Comment by Sn3b** [comment]
Thanks ;)

**Comment by flauc** [comment]
This is now fully implemented. Sorry for the long wait.

**Comment by Sn3b** [comment]
Nice, thanks :)
