### ISSUE TITLE
Adding SimpleNotificationsModule to @NgModule Imports causes 

### ISSUE THREAD

**Issue by tiangco** [flauc/angular2-notifications#137]
When I include "SimpleNotificationsModule" with my imports , it causes this error.
Seems to be related to loading the "rxjs/Notification.js"

Error: ReflectionCapabilities</ReflectionCapabilities.prototype.parameters@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2118:36
	Reflector</Reflector.prototype.parameters@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:2319:24
	CompileMetadataResolver</CompileMetadataResolver.prototype.getDependenciesMetadata@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14336:65
	CompileMetadataResolver</CompileMetadataResolver.prototype.getTypeMetadata@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14301:23
	CompileMetadataResolver</CompileMetadataResolver.prototype.getDirectiveMetadata@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14074:25
	CompileMetadataResolver</CompileMetadataResolver.prototype.getNgModuleMetadata/<@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14143:45
	CompileMetadataResolver</CompileMetadataResolver.prototype.getNgModuleMetadata@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14136:19
	CompileMetadataResolver</CompileMetadataResolver.prototype.getNgModuleMetadata/<@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:46
	CompileMetadataResolver</CompileMetadataResolver.prototype.getNgModuleMetadata@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:19
	RuntimeCompiler</RuntimeCompiler.prototype._compileComponents@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16803:26
	RuntimeCompiler</RuntimeCompiler.prototype._compileModuleAndComponents@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16741:34
	RuntimeCompiler</RuntimeCompiler.prototype.compileModuleAsync@http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16732:18
	PlatformRef_</PlatformRef_.prototype._bootstrapModuleWithZone@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:6954:20
	PlatformRef_</PlatformRef_.prototype.bootstrapModule@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:6936:20
	@http://localhost:3000/app/main.js:5:1
	@http://localhost:3000/app/main.js:1:31
	@http://localhost:3000/app/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:232:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:114:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:502:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:265:21
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:154:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:401:25
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:339:25
	
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
http://localhost:3000/node_modules/systemjs/dist/system.src.js
Line 123

**Comment by ramiresnas** [comment]
Are you trying to inject some dependency into class constructor ?
