### ISSUE TITLE
Notification Singleton use

### ISSUE THREAD

**Issue by GuillaumeUnice** [flauc/angular2-notifications#14]
Hello,
It's not a problem, I just want an information, It's possible to include : SimpleNotificationsComponent in AppComponent in order to use them for all child AppComponent?

Because, currently when I want to use notification, I must include in all child template : 
`<simple-notifications [options]="options"></simple-notifications>  `

Thanks for advice

**Comment by flauc** [comment]
Yes it is. You only need to create one instance of the SimpleNotificationsComponent and the main AppComponent is a great place to do that. 

Then you only need to include the NotificationsService in any component from which you want to instantiate a notification.

**Comment by GuillaumeUnice** [comment]
Lol! It's was so simply!

Thanks ;)
