### ISSUE TITLE
No provider for NotificationsService

### ISSUE THREAD

**Issue by andy200486** [flauc/angular2-notifications#151]
I've installed the latest version (0.4.53) and get this error : 

> error_handler.js:47EXCEPTION: Uncaught (in promise): Error: No provider for NotificationsService!

I got this in my app.module : 
`declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        SimpleNotificationsModule.forRoot()
    ],
    providers: [
        NotificationsService
    ],
    bootstrap: [AppComponent]`

Could someone give me some help ?

Thanks

**Comment by flauc** [comment]
Hey @andy200486 

In your providers you don't need the `NotificationService. Just import the module and you should be good to go.

**Comment by andy200486** [comment]
Hi @flauc 

Thanks for your quick response!
I've remove the NotificationsService inside the providers array but I still got the same issue.

Any others ideas ?

Thanks

**Comment by flauc** [comment]
Huh, I must be missing something. 

Here is a quick plunker from a nother issue: 

https://plnkr.co/edit/abk2b0

It's not related but it demonstrates the basic setup. If this doesn't help could you please try and recreate the issue in a plunker?

**Comment by andy200486** [comment]
Thanks for your plunker. 
My fault, I've forgotten to put the provider for the service inside app.component.

Thanks!

**Comment by flauc** [comment]
Glad you got it working 👍
