### ISSUE TITLE
No notification seen for html(html: any, type: string, override?: any) method

### ISSUE THREAD

**Issue by atapas** [flauc/angular2-notifications#152]
Not able to see the notification for

```js

html(html: any, type: string, override?: any)

```

I see the dom element is getting added. Not sure if it is some issue with positioning.

Here is the Plunker Link: https://plnkr.co/edit/FygmCl?p=preview

Here is the console:

![image](https://cloud.githubusercontent.com/assets/3633137/22781638/5c09ce1a-eee9-11e6-8a49-e564c0873751.png)

**Comment by flauc** [comment]
Hi @atapas 

Thanks for the great issue report, when I get a plunker like this it makes it a lot easier to identify the problem. 

So as the `type` you need to pass a desired notification type. Take a look at this fork of the plunker:

https://plnkr.co/edit/abk2b0

**Comment by atapas** [comment]
Ah.. ok that works. I will close the issue.
