### ISSUE TITLE
excuted Angular-cli Aot error : Cannot read property 'text' 

### ISSUE THREAD

**Issue by crper** [flauc/angular2-notifications#153]
1.  `ng build --prod `
```javascript
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
```

2 . angular2-notifications v0.4.53

3 . Error

![image](https://cloud.githubusercontent.com/assets/8272877/22815941/c69b5144-ef99-11e6-92b0-51783668f36f.png)

Thanks....

**Comment by mab** [comment]
I couldn't reproduce the error, but I'm using a more current Node version. `ng build --prod` and `ng build --prod --aot` are running without error.

```@angular/cli: 1.0.0-beta.31
node: 7.2.1
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
angular2-notifications: 0.4.53
```

**Comment by crper** [comment]
@mab   how to do import and use？  

```
import { SimpleNotificationsModule } from 'angular2-notifications';
import { NotificationsService } from 'angular2-notifications';
@NgModule( {
  declarations: [
    AppComponent,
    // ...pipe
  ],
  imports: [
    ...fncModules,
    ...businessModules,
    AppRoutes,
  ],
  exports: [
  ],
  providers: [ AuthService, EventsService, NotificationsService, AppService ],
  bootstrap: [ AppComponent ],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
```


 when build `-aot` throw  error

**Comment by mab** [comment]
Please read the Setup section in the [documentation](https://github.com/flauc/angular2-notifications/blob/master/docs/toastNotifications.md). 

Your `AppModule` misses the import Statement `SimpleNotificationsModule.forRoot(),` in the imports section. The documentation is pretty straight forward.

**Comment by crper** [comment]
@mab sorry , screenshoot no entire , i include need dependice 
![image](https://cloud.githubusercontent.com/assets/8272877/23024379/f90f07e2-f494-11e6-9d33-ccdb8800d37f.png)

![image](https://cloud.githubusercontent.com/assets/8272877/23024993/514a7520-f497-11e6-8b82-e02caf0c5ae4.png)

**Comment by mab** [comment]
Could you please provide a minimal example to reproduce the error? Plain Angular project and no further dependencies.

**Comment by crper** [comment]
@mab [ this is minial example repository](https://github.com/zjcboy/test-notifications/)   , please test ; thanks , can't excute `ng build --prod --aot`[can't success throw error ]

**Comment by mab** [comment]
I cloned your repository.  `ng build --prod` successful. `ng serve`works fine as well and the button click shows your frustrated success message.

I tested it this time on a different environment.

```@angular/cli: 1.0.0-beta.31
node: 7.5.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
```
I recommend updating your Node version.

**Comment by crper** [comment]
@mab   Thanks ,  but i try again error , my only copy this  module and component  code  with my project , [myself ]new module can useful ..no error

**Comment by crper** [comment]
clo
