### ISSUE TITLE
 Cannot find type definition file for 'core-js'

### ISSUE THREAD

**Issue by djleonskennedy** [flauc/angular2-notifications#159]
[at-loader] node_modules\angular2-notifications\lib\notification.type.d.ts:1:1 
    TS2688: Cannot find type definition file for 'core-js'.

**Comment by tmakin** [comment]
Just ran into this. I fixed it by hacking `notification.type..d.ts` file as recommended in #136. Not ideal, but it has sorted things out until a proper fix is found.
