### ISSUE TITLE
Cannot read property 'unsubscribe' of undefined

### ISSUE THREAD

**Issue by andrzejpiasecki** [flauc/angular2-notifications#16]
I use authorization component which checks if user is authorize to see protected page where I have <simple-notifications> and SimpleNotificationsComponent. In case of unauthorized attempt, the authorization component uses Router and navigates to login page. And in that case I got:

Unhandled promise rejection TypeError: Cannot read property 'unsubscribe' of undefined(…)

which leads to NotificationComponent and:

ngOnDestroy() { this.listener.unsubscribe() }

It is probably because of component not being initializes in ngOnInit.

**Comment by flauc** [comment]
Hi, i've added a fix i think might work. The update is live, can you let me know how it goes?
