### ISSUE TITLE
Warning in web console

### ISSUE THREAD

**Issue by minato-namikaze** [flauc/angular2-notifications#161]
Hello,
We are having warning onto the web console.
It's minor and not a problem but for an enterprise class application it's still a burden.
A fix would be appreciated
![notifbug](https://cloud.githubusercontent.com/assets/25571847/23740018/eebe7184-04a1-11e7-800c-75ae76510aa4.png)

**Comment by flauc** [comment]
Hi @minato-namikaze 

This is because the src folder is published as well as dist. You can exclude it manually in your tslint. There is also a discussion on this subject here #162 feel free to join in 👍

**Comment by flauc** [comment]
Closing it in favor of #162
