### ISSUE TITLE
Do not publish .ts files on npmjs.org

### ISSUE THREAD

**Issue by victornoel** [flauc/angular2-notifications#162]
Hi,

Apparently, `angular2-notifications` is published on npmjs.org with its `ts` files.
This is a bad practice according to (at least) angular-cli people (see https://github.com/angular/angular-cli/issues/4675#issuecomment-285694210).

It would be great if the `ts` files were removed in future releases and optionally for the latest release too :)

Thanks!

**Comment by flauc** [comment]
Hi @victornoel 

Sorry for responding so late. 
I'm not sure about this one, why is this a bad practice? 

Initially the src folder was excluded from the library but I got a lot of complaints about it.

**Comment by xealot** [comment]
#111 explains why it breaks things. Unless something has changed it still holds true.

**Comment by flauc** [comment]
Yes, but can't you exclude node_modules from your tsconfig and tslint?

**Comment by xealot** [comment]
`node_modules` is excluded by default I believe. When you include things from `node_modules` when typescript sees a ".d.ts" file and a ".ts" file in the same place it will look at the `ts` file. 

Do you know of any other TS libraries that ship `ts` source code with the NPM module?

**Comment by victornoel** [comment]
I agree with @flauc that it is not a good enough reason: @xealot `node_modules` is NOT ignored by default, and you could/should ignore it.

I initially reported this issue because I understood from angular people that it was a bad practice (as you say @xealot, there is almost no npm module shipping their ts files). But I'm not exactly sure WHY it is a bad practice, I asked @filipesilva (https://github.com/angular/angular-cli/issues/4675#issuecomment-292889291) about it and I'm waiting for an answer.

Personally, I like the fact that ts files are present because I can browse the code of the dependencies I use, but it still seems it is not a practice usually followed…

**Comment by filipesilva** [comment]
Copied from https://github.com/angular/angular-cli/issues/4675#issuecomment-292946255

>>>
@victornoel generally it's discouraged to ship TypeScript with third party libraries because it would require the consumer to replicate the complete build environment of the library. Not only typings, but potentially a specific version of `ngc` as well.

Publishing plain JavaScript with typings and meta data allows the consuming application to remain agnostic of the library's build environment.

**Comment by xealot** [comment]
The point still remains that if you use the "rootDir" option in your code and it's pointed to something like `src` this will break projects.

Which means your library isn't compatible with a subset of projects that use this TS feature. Additionally, if I exclude `node_modules` will that still type-check the things I import from there?

**Comment by victornoel** [comment]
@xealot you are right that there may be strange behaviour with respect to tslint typechecking if you remove `node_modules`! I didn't think of that :)

Thanks @filipesilva for the explanation.

**Comment by flauc** [comment]
I'll remove the src folder from the published repo, with everything you pointed out I think there really isn't any point in having it in there. 

Thank you for joining in and helping out 👍

**Comment by flauc** [comment]
It looks like this actually breaks my build. Reverting back to having it in there for now.

**Comment by victornoel** [comment]
Hi @flauc, I'm back on this.

I really think you should take this issue into account, here is another reason: https://github.com/Microsoft/TypeScript/issues/15363

Basically, when shipping ts files with your package, they get taken into account by tsc and can create problems .
Actually, yours is creating problem for me, I get the following error when using `noImplicitAny`:
```
ERROR in .../frontend/node_modules/angular2-notifications/src/simple-notifications/services/notifications.service.ts (51,72): Element implicitly has an 'any' type because type 'Icons' has no index signature.
```

**Comment by t-p-l-k** [comment]
Also, Angular CLI incremental builds using `ng serve` seems to cause full angular2-notifications rebuild on any change.
Maybe I'm wrong but that's what I always see:
![image](https://user-images.githubusercontent.com/20531968/35341597-1318887a-0137-11e8-93e4-59defb334cac.png)

**Comment by flauc** [comment]
The latest version no longer publishes .ts files
