### ISSUE TITLE
Tslint errors when launching npm run lint

### ISSUE THREAD

**Issue by Spike81** [flauc/angular2-notifications#163]
Hi, I am experiencing some problems with linting.
I've installed this module through npm, as explained in readme, my app is already configured to skip node_modules directory when but jenkins launchs npm run lint (or lint is run in local environment, it doesn't matter), build cannot be completed because are thrown some linting errors in `node_modules/angular2-notifications/src/` files. 

Any idea why this is happening or any thoughts about some configuration options to avoid this problem?

Any help would be appreciated, thanks in advance.

relevant infos about this issue:
- `"angular2-notifications": "0.4.53"` from my `package.json`
- `"lint:f": "tslint -c ./tslint.json  --project ./tsconfig.json --type-check --exclude app/app.route.ts"` from my `package.json`
- `"exclude": [
        "node_modules",
        "doc",
        "**/*.spec.ts",
        "node_modules/angular2-notifications/*.*"
    ],` from my `tsconfig.json`

**Comment by flauc** [comment]
Hi @Spike81 

I think this last push cleared up the lint issues, thanks for reporting it, let me know if you keep getting the error.

**Comment by sfabriece** [comment]
This is still happening with me
