### ISSUE TITLE
How do i correctly import it?

### ISSUE THREAD

**Issue by dearibujar** [flauc/angular2-notifications#164]
I have more modules beside the appmodule. On  one of the other modules called MessageModule i have a componenet where i want to use push notifications. How do i correctly import it ?
Should i import it on the app module or directly on the MessageModule.

**Comment by flauc** [comment]
Hi @dearibujar you should import it on the AppModule like this: 

```
imports: [
        BrowserModule,
        // Animations need to be imported in to your project to use the library
        BrowserAnimationsModule, 
        SimpleNotificationsModule.forRoot()
    ],
```

You can then use it in both modules.
