### ISSUE TITLE
Icons cannot be overridden

### ISSUE THREAD

**Issue by MrFranke** [flauc/angular2-notifications#165]
Hi! I can't set custom icons for notifications.
Options:
```
public notieOptions = {
    theClass: 'custom',
    position: ['top', 'right'],
    maxLength: 10,
    showProgressBar: false,
    pauseOnHover: true,
    animate: 'fromRight',
    icons: {
      success: '<i class="ico ok_green"></i>'
    }
  };
```

**Comment by pmcochrane** [comment]
I can't seem to get this to work either. Trying to use font-awesome icons instead of the build in SVG's.

Icons property seems to be completely ignored if you specify at initialization or when displaying a notification.

**Comment by hindmarch** [comment]
I've managed to get this to work by specifying the icon after the notification's been defined:

```
const notification = this.notificationService.success(toast.title, toast.message);
notification.icon = '<em class="fa fa-4x fa-check-circle"></em>';
```

Otherwise I'm unable to define my own icon at all.

**Comment by mkollers** [comment]
I've found a workaround! Just import the default icons, and override them:

import { defaultIcons} from 'angular2-notifications';
defaultIcons.success = '...my-fancy-icon...';

**Comment by ganeshkantu** [comment]
@mkollers are you overriding with the CSS of the new icon or the HTML?

**Comment by mkollers** [comment]
HTML, I'm using SVGs

**Comment by reco** [comment]
can you guys make a release? we cannot pull from master (security compliance) but need this change.

**Comment by flauc** [comment]
hmm, hasn't this bean pushed already?

**Comment by mkollers** [comment]
npm release 0.7.6 has solved it for me :-)
