### ISSUE TITLE
Is there any compat issue with angular 4 ?

### ISSUE THREAD

**Issue by Rebolon** [flauc/angular2-notifications#168]
I'm trying the component with angular4 and i have some issue :
 * needs to remove the [] around options : <simple-notifications options="options"></simple-notifications>
* options doesn't seem to be used : everything is default values because the toast appear on bottom right and never disappear which is not what i set in options (even if i force the options in success call it doesn't work)

`

@Component({
  selector: 'app-notifications',
  templateUrl: '<simple-notifications options="options"></simple-notifications>',
  styleUrls: ['./notifications.component.scss']
})
export class NotificationsComponent implements OnInit {
  public options: {
    position: ['top', 'right'],
    timeOut: 3000,
    preventDuplicates: true
  }

  constructor(protected notifications: PeaksNotifs, protected toaster: NotificationsService) { }

  ngOnInit() {
    this.notifications.message.subscribe((notif: Notifications) => {
      if (notif.type !== NotificationsType.success) {
        this.toaster.success('Success', notif.message, this.options)
      } else {
        this.toaster.error('Error', notif.message)
      }
    })
  }
}

`

**Comment by bomberblue07** [comment]
@Rebolon look at the discussion in #169 and see if the solutions mentioned worked for you

**Comment by Rebolon** [comment]
thx
