### ISSUE TITLE
 Error: Found the synthetic property @enterLeave

### ISSUE THREAD

**Issue by shibulijack** [flauc/angular2-notifications#170]
Angular 4 requires either "BrowserAnimationsModule" or "NoopAnimationsModule" to be included for animations to work.

Import the new BrowserAnimationsModule from @angular/platform-browser/animations in your root NgModule. Without this, your code will compile and run, but animations will trigger an error. Imports from @angular/core were deprecated, use imports from the new package import { trigger, state, style, transition, animate } from '@angular/animations';

> angular2-notifications/src/notification.component.ts

**Comment by treeder** [comment]
Thanks, helped with a different library I was using too.

**Comment by isener** [comment]
thanks mate

**Comment by mezza** [comment]
I've added:
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`
to root NgModule and then registered the model in my @NgModule.imports and seems to fix it.

**Comment by raff90** [comment]
Thanks

**Comment by trsh** [comment]
I get this error for lazy loaded modules :/, even with the above steps.

**Comment by flauc** [comment]
I think this has just been resolved with the latest release. Please let me know if you're still seeing it though.

**Comment by dracan** [comment]
@flauc Just letting you know that I'm getting this in 0.9.7. Following @mezza's instructions above fixed it.

**Comment by jainAdijain** [comment]
I am still seeing the error in lazy loaded modules

**Comment by flauc** [comment]
This actually is in the documentation already.
