### ISSUE TITLE
Wrap text for long notifications

### ISSUE THREAD

**Issue by maxime1992** [flauc/angular2-notifications#173]
When a notification has some long text, it goes outside of the notif :

![image](https://cloud.githubusercontent.com/assets/4950209/24497465/cda41148-153b-11e7-8973-aabf82c62fe4.png)

**Comment by flauc** [comment]
Hi @maxime1992 ,

Sorry for responding so slowly. 
Currently you have two options. You can edit the style of `.simple-notification` and give it a bigger height so the text fits, or you can limit the length of the text through the options `maxLength: 10`

**Comment by maxime1992** [comment]
No commit ref, is this fixed? :)

**Comment by flauc** [comment]
What is there to fix?

**Comment by maxime1992** [comment]
Shouldn't this be by default?

> You can edit the style of .simple-notification and give it a bigger height so the text fits

**Comment by flauc** [comment]
In the latest version, the text won't break the style. Try adding a long title or content here: 

https://stackblitz.com/edit/angular2-notifications-example
