### ISSUE TITLE
Can't change alert position

### ISSUE THREAD

**Issue by rvgarimrj** [flauc/angular2-notifications#178]
Can't make alert change position. Tried this code:

this.NotificationsService.error(
          'Erro de cadastro',
          e.error.json().errors.full_messages[0],
          {
              position: ["top", "left"],
              timeOut: 5000,
              showProgressBar: true,
              pauseOnHover: false,
              clickToClose: true,
              lastOnBottom: true,
              animate: "fromLeft"
          }
        );

but the notification alert is still positioned on top right.

any ideas ?

**Comment by flauc** [comment]
Hi @rvgarimrj 

I'm sorry bug only this options can be overridden through the service: 

id
animate
timeOut
showProgressBar
pauseOnHover
clickToClose
maxLength
theClass
icon

If you want to change the position you need to pass that option in to the component `<simple-notifications [options]="options"></simple-notifications>`

**Comment by minato-namikaze** [comment]
It would be good to fix it !

**Comment by flauc** [comment]
It's not a bug it's just not how the notifications were designed.
