### ISSUE TITLE
Test angular2 Notifications

### ISSUE THREAD

**Issue by GuillaumeUnice** [flauc/angular2-notifications#18]
Hi every,
I just a request I want to test my Angular2 App with Karma. But when I tried to include angular2 notification into Karma it's return.
`exports is not defined`

Because  I think module and file component.js don't support CommonJS, require and export.

You have schedule to testing angular2 Notification or not at all?

Thanks for answer

**Comment by flauc** [comment]
Hi, 

I'm not really sure what your particular problem is but if you check the tsconfige.json in the root folder you will see that the ts files actually compile to commonJs.

**Comment by GuillaumeUnice** [comment]
Ok, I just want to import in my test notification.

And I don't know if I can import directly the components.js or if I must use a preprocessor?

This my karma config : 
[https://codeshare.io/wpOXk](url)

And the line in files array: 
`{ pattern: 'node_modules/angular2-notifications/components.js', included: true, watched: true },`
return `exports is not defined` in my terminal.

Maybe a preprocessor commonJs for testing?

**Comment by vladotesanovic** [comment]
@GuillaumeUnice 

Add it like:

```javascript
{ pattern: 'node_modules/angular2-notifications/**/*.js', included: false, watched: false },
```

**Comment by oehm-smith** [comment]
Howdy, testing isn't working for me.

`npm start` works fine and notifications are displayed.  But the tests are failing to load something.

1. `npm test` gives the error:

    WARN [web-server]: 404: /node_modules/angular2-notifications/package.json


I add the following to `karma.conf.js`:

    { pattern: 'node_modules/angular2-notifications/**/*.js', included: false, watched: false },

2. Error now:

    WARN [web-server]: 404: /base/node_modules/angular2-notifications.js
       
`angular2-notifications.js` is not in the `angular2-notifications` module and there is no reference to it either.  I don't know why there is a dependency on this.

5. Perhaps this needs to be mapped.  Add the following to test-config.js.

    'angular2-notifications': 'node_modules/angular2-notifications',
    
The file is now:

    // Load our SystemJS configuration.
    System.config({
      baseURL: '/base/',
      map: {
          'moment': 'moment/moment',
          'ng2-bootstrap': 'ng2-bootstrap/ng2-bootstrap',
    
           'angular2-notifications': 'node_modules/angular2-notifications',
       }
     });


The error is now:

    WARN [web-server]: 404: /base/node_modules/node_modules/angular2-notifications.js
    
So simple substitution seems to be going on.  Play with this mapping.

No improvements.  Return to original value.

6. Try adding package as specified at https://www.npmjs.com/package/angular2-notifications to the `test-config.js`.  This file is now:

         // Load our SystemJS configuration.
        System.config({
          baseURL: '/base/',
          map: {
              ...
              'angular2-notifications': 'node_modules/angular2-notifications',
          },
            packages: {
                'angular2-notifications': {
                    main: 'components.js',
                    defaultExtension: 'js'
                }
            }
        });
Still not working.  Error is:

WARN [web-server]: 404: /base/node_modules/node_modules/angular2-notifications.js

Any help would be appreciated.
