### ISSUE TITLE
Error with Angular 4

### ISSUE THREAD

**Issue by duard** [flauc/angular2-notifications#181]
I cant use this with Angular 4 project

Failed to compile.
`import { NotificationsService, SimpleNotificationsComponent, Options, PushNotificationsService } from 'angular2-notifications';

/home/golveia/Desenvolvimento/app-pontal/src/app/app.component.ts (3,62): Module '"/home/golveia/Desenvolvimento/app-pontal/node_modules/angular2-notifications/components"' has no exported member 'Options'.`

If I remove the Options I can run the app, but another error : 

`zone.js:569 Unhandled Promise rejection: No provider for NotificationsService! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for NotificationsService!`

My app module : 

```
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ApplicationRef, ErrorHandler } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { SimpleNotificationsModule, PushNotificationsModule } from 'angular2-notifications';
import { LoggingService, GlobalErrorHandler } from './global/error-handler.service';
import { routes } from './app.routes';
import { SharedModule } from './shared/shared.module';
import { AuthenticationModule } from './authentication/authentication.module';
import { FrontendModule } from './frontend/frontend.module';
import { BackendModule } from './backend/backend.module';
import { AppComponent } from './app.component';
import { ErrorHandlerComponent } from './global/error-handler/error-handler.component';

@NgModule({
  declarations: [
    AppComponent,
    ErrorHandlerComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    BrowserAnimationsModule,
    SimpleNotificationsModule,
    PushNotificationsModule,
    RouterModule.forRoot(routes, { useHash: false }),

    SharedModule,
    AuthenticationModule,

    FrontendModule,
    BackendModule
  ],
  providers: [
    LoggingService,
    {
      provide: ErrorHandler,
      useClass: GlobalErrorHandler
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
`
```

If I put the services on PROVIDERS the app RUN but I cant see any notifications (html) .. only push notifications work.

**Comment by floriane-retinad** [comment]
Hi there!
I had the same `No provider for NotificationsService!` error with Angular 4, you can find informations and temporary fix in issue #146.

**Comment by flauc** [comment]
Just made some mayor refactoring for ng4,
Please let me know if you are still getting this error with the newest version, thanks.

**Comment by duard** [comment]
Sorry man, it works good, I just start a new project and isolated this modules in one of my modules and now everything works :+1:

**Comment by flauc** [comment]
That's great, thanks for the quick response 👍

**Comment by dojchek** [comment]
@flauc 
Thanks man! I just noticed that the warnings are also gone, except one: 'peer dependency to @angular/platform-browser. That one is still on `^2.1.1` version.

Here's the exact warning message:
`warning "angular2-notifications@0.5.2" has incorrect peer dependency "@angular/platform-browser@^2.1.1"`

Would be nice to get that one done as well - Although everything is fully functional 👍

**Comment by flauc** [comment]
Looks like I missed that one, got it now, thanks man!

**Comment by dojchek** [comment]
Wow MAN!
That was amazingly fast!! 
I just ran `yarn upgrade-interactive` to fix other ng4 deps, and it offered me upgrade to *angular2-notifications@0.5.3*
Just few minutes after I upgraded to 0.5.2 :)
🥇 GJ
