### ISSUE TITLE
Error on Angular 4 - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by psaussure** [flauc/angular2-notifications#184]
I tried importing angular2-motifications in my angular CLI project. I'm unable to even load the page since an error occurs.

Angular version: 4.0.1
CLI version: 1.0.0

# Package.json
```
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/compiler-cli": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/platform-server": "~4.0.0",
    "@angular/router": "~4.0.0",
    "angular2-notifications": "^0.5.3",

    ......
```

# App.module.ts

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { SimpleNotificationsModule } from 'angular2-notifications';
import { AppRoutingModule } from './app.routing';
import { AppComponent } from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    RouterModule,
    HttpModule,
    FormsModule,
    ReactiveFormsModule,
    BrowserAnimationsModule,
    
    SimpleNotificationsModule.forRoot(),
    
    // Routing
    AppRoutingModule
  ],
  declarations: [
    AppComponent
  ],
  providers: [
    // Router hash location strategy
    {
      provide: LocationStrategy,
      useClass: HashLocationStrategy
    }
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }

```

# AppComponent
```typescript
import { Component } from '@angular/core';
import { SimpleNotificationsComponent } from 'angular2-notifications';

@Component({
  selector: 'app-root',
  template: '<h1>Hello Angular</h1><simple-notifications [options]="options"></simple-notifications>'
})
export class AppComponent { }
```

# Full Error

> ERROR TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at SimpleNotificationsComponent.attachChanges (simple-notifications.component.js:126)
>     at SimpleNotificationsComponent.set options [as options] (simple-notifications.component.js:37)
>     at updateProp (core.es5.js:10972)
>     at checkAndUpdateDirectiveInline (core.es5.js:10669)
>     at checkAndUpdateNodeInline (core.es5.js:12090)
>     at checkAndUpdateNode (core.es5.js:12058)
>     at debugCheckAndUpdateNode (core.es5.js:12687)
>     at debugCheckDirectivesFn (core.es5.js:12628)
>     at Object.eval [as updateDirectives] (AppComponent.html:1)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12613)
>     at checkAndUpdateView (core.es5.js:12025)
>     at callViewAction (core.es5.js:12340)
>     at execComponentViewsAction (core.es5.js:12286)
>     at checkAndUpdateView (core.es5.js:12031)

> Unhandled Promise rejection: Cannot convert undefined or null to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at SimpleNotificationsComponent.attachChanges (simple-notifications.component.js:126)
>     at SimpleNotificationsComponent.set options [as options] (simple-notifications.component.js:37)
>     at updateProp (core.es5.js:10972)
>     at checkAndUpdateDirectiveInline (core.es5.js:10669)
>     at checkAndUpdateNodeInline (core.es5.js:12090)
>     at checkAndUpdateNode (core.es5.js:12058)
>     at debugCheckAndUpdateNode (core.es5.js:12687)
>     at debugCheckDirectivesFn (core.es5.js:12628)
>     at Object.eval [as updateDirectives] (AppComponent.html:1)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12613)
>     at checkAndUpdateView (core.es5.js:12025)
>     at callViewAction (core.es5.js:12340)
>     at execComponentViewsAction (core.es5.js:12286)
>     at checkAndUpdateView (core.es5.js:12031) TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at SimpleNotificationsComponent.attachChanges (http://localhost:4200/vendor.bundle.js:68045:16)
>     at SimpleNotificationsComponent.set options [as options] (http://localhost:4200/vendor.bundle.js:67956:14)
>     at updateProp (http://localhost:4200/vendor.bundle.js:44682:37)
>     at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:44379:19)
>     at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:45800:17)
>     at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:45768:16)
>     at debugCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:46397:59)
>     at debugCheckDirectivesFn (http://localhost:4200/vendor.bundle.js:46338:13)
>     at Object.eval [as updateDirectives] (ng:///AppModule/AppComponent.ngfactory.js:24:5)
>     at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:4200/vendor.bundle.js:46323:21)
>     at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:45735:14)
>     at callViewAction (http://localhost:4200/vendor.bundle.js:46050:17)
>     at execComponentViewsAction (http://localhost:4200/vendor.bundle.js:45996:13)
>     at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:45741:5)
> consoleError @ zone.js:569
> handleUnhandledRejection @ zone.js:574
> _loop_1 @ zone.js:609
> drainMicroTaskQueue @ zone.js:613

> Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to object
> TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at SimpleNotificationsComponent.attachChanges (simple-notifications.component.js:126)
>     at SimpleNotificationsComponent.set options [as options] (simple-notifications.component.js:37)
>     at updateProp (core.es5.js:10972)
>     at checkAndUpdateDirectiveInline (core.es5.js:10669)
>     at checkAndUpdateNodeInline (core.es5.js:12090)
>     at checkAndUpdateNode (core.es5.js:12058)
>     at debugCheckAndUpdateNode (core.es5.js:12687)
>     at debugCheckDirectivesFn (core.es5.js:12628)
>     at Object.eval [as updateDirectives] (AppComponent.html:1)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12613)
>     at checkAndUpdateView (core.es5.js:12025)
>     at callViewAction (core.es5.js:12340)
>     at execComponentViewsAction (core.es5.js:12286)
>     at checkAndUpdateView (core.es5.js:12031)
>     at Function.keys (<anonymous>)
>     at SimpleNotificationsComponent.attachChanges (simple-notifications.component.js:126)
>     at SimpleNotificationsComponent.set options [as options] (simple-notifications.component.js:37)
>     at updateProp (core.es5.js:10972)
>     at checkAndUpdateDirectiveInline (core.es5.js:10669)
>     at checkAndUpdateNodeInline (core.es5.js:12090)
>     at checkAndUpdateNode (core.es5.js:12058)
>     at debugCheckAndUpdateNode (core.es5.js:12687)
>     at debugCheckDirectivesFn (core.es5.js:12628)
>     at Object.eval [as updateDirectives] (AppComponent.html:1)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12613)
>     at checkAndUpdateView (core.es5.js:12025)
>     at callViewAction (core.es5.js:12340)
>     at execComponentViewsAction (core.es5.js:12286)
>     at checkAndUpdateView (core.es5.js:12031)
>     at resolvePromise (zone.js:712) [<root>]
>     at resolvePromise (zone.js:683) [<root>]
>     at :4200/polyfills.bundle.js:6475:17 [<root>]
>     at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:165) [<root> => <root>]
>     at drainMicroTaskQueue (zone.js:593) [<root>]

**Comment by flauc** [comment]
HI @psaussure,

It looks like you are not passing in any options in the `AppComponent` can you try doing this: 

```ts
export class AppComponent {
  public options = {
    position: ["bottom", "left"],
    timeOut: 5000,
    lastOnBottom: true
  }
}
```

**Comment by psaussure** [comment]
Ok... my bad. It's indeed the case.

**Comment by flauc** [comment]
No problem, glad it works now 👍

**Comment by vbenavidesa** [comment]
Hi flauc,

I am having the same issue, but I have the options in my Component. I have the Module on my root app.module.ts and the tags on the app.component.html and I am trying to use it from another component where I use the public options but still getting the error on loading and no notification when executed!
