### ISSUE TITLE
Overriding maxStack or dismissing previous messages from service

### ISSUE THREAD

**Issue by psaussure** [flauc/angular2-notifications#185]
Now I got the module works properly, the notifications appears without problem. The default `maxStack` was not touched in the `options` passed on 

I have my AppComponent including:
`<simple-notifications [options]="notificationsOptions"></simple-notifications>`

and in ts part (thanks @flauc ...)
```
public notificationsOptions = {
    position: ["middle", "right"],
    timeOut: 3000,
    lastOnBottom: true,
    maxStack: 5
  }
```

Here is my case:

 - When clicking on a refresh button, trigger a message with notification service:
```
this._notificationService.info('Request', 'Refreshing application list'};
```
- It triggers a http request. Which takes about less than 1 second to execute. Then I notify the user:
```
this._notificationService.success('Request completed', 'Refresh completed');
```

But since the refresh completed message occurs very quickly after the pending "refreshing" message, I would like, on the success, to remove the old "pending" notification.

I tried to set
`this._notificationService.success('Request completed', 'Refresh completed', {maxStack: 1}):`

but it doesn't remove the previous message. I also tried to add the `maxStack: 1` override in the `.info() ` call without more success.

**How to, from service, dismiss immediate previous alert? Or how to override the maxStack just for a given action / notification pool.**

**Comment by psaussure** [comment]
I understand this could be done with `remove()` method but I will make maybe my question clearer/more specific: how to retrieve the ID of the last notification emitted. To be able to remote it.

**Comment by blackholegalaxy** [comment]
Any news on that? I'm also interested in retrieving ID of notification.

**Comment by flauc** [comment]
Hi guys,

Sorry missed this one. So each method on the service returns the notification. 

```ts
  set(notification: Notification, to: boolean) {
    notification.id = notification.override && notification.override.id ? notification.override.id : Math.random().toString(36).substring(3);
    notification.click = new EventEmitter<{}>();
    this.emitter.next({command: 'set', notification: notification, add: to});
    return notification;
  };

  success(title: string, content?: string, override?: any) {
    return this.set({title: title, content: content || '', type: 'success', icon: this.icons.success, override: override}, true);
  }
```

**Comment by flauc** [comment]
You can also listen to the onCreate event on the component `<simple-notifications (onCreate)="something($event)"></simple-notifications>`

**Comment by blackholegalaxy** [comment]
Thanks it helps!
