### ISSUE TITLE
testing on PhantomJS fails

### ISSUE THREAD

**Issue by psaussure** [flauc/angular2-notifications#186]
When I try to test my component using angular2-notifications, I encounter an error:

```
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///~/angular2-notifications/dist/src/simple-notifications/services/notifications.service.js:9:0 <- src/test.ts:29912
```

Full error log:

```
10 04 2017 12:40:31.072:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
10 04 2017 12:40:31.075:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 04 2017 12:40:31.080:INFO [launcher]: Starting browser PhantomJS
10 04 2017 12:40:34.655:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket KbzJcvPpIbxewr_5AAAA with id 21604446
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///~/angular2-notifications/dist/src/simple-notifications/services/notifications.service.js:9:0 <- src/test.ts:29912

Finished in 0.511 secs / 0 secs @ 12:40:35 GMT-0400

SUMMARY:
√ 0 tests completed
```

With chrome, the error doesn't occur. Do you have any idea?

**Comment by psaussure** [comment]
Maybe this could be because of ES6 targetting.

**Comment by sureshokp** [comment]
`Error on fetch for node_modules/angular2-notifications/src/simple-notifications.module.js at file:///D:/GIP/IMAGE PILOT/gipfe/node_modules/angular2-notifications/src/simple-notifications.module.js Loading build/tmp/aot/src/app/app.module.ngfactory.js Loading build\boot-aot.js Error: ENOENT: no such file or directory, open 'D:\GIP\IMAGE PILOT\gipfe\node_modules\angular2-notifications\src\simple-notifications.module.js' [10:13:51] 'build.aot' errored after 52 s [10:13:51] Error in plugin 'run-sequence(bundle-aot)' Message: Error on fetch for node_modules/angular2-notifications/src/simple-notifications.module.js at file:///D:/GIP/IMAGE PILOT/gipfe/node_modules/angular2-notifications/src/simple-notifications.module.js Loading build/tmp/aot/src/app/app.module.ngfactory.js Loading build\boot-aot.js ENOENT: no such file or directory, open 'D:\GIP\IMAGE PILOT\gipfe\node_modules\angular2-notifications\src\simple-notifications.module.js' Details: originalErr: Error: ENOENT: no such file or directory, open 'D:\GIP\IMAGE PILOT\gipfe\node_modules\angular2-notifications\src\simple-notifications.module.js' Stack: Error on fetch for node_modules/angular2-notifications/src/simple-notifications.module.js at file:///D:/GIP/IMAGE PILOT/gipfe/node_modules/angular2-notifications/src/simple-notifications.module.js Loading build/tmp/aot/src/app/app.module.ngfactory.js Loading build\boot-aot.js Error: ENOENT: no such file or directory, open 'D:\GIP\IMAGE PILOT\gipfe\node_modules\angular2-notifications\src\simple-notifications.module.js'`

build error is came after i update node modules using **npm install** command then, i try to take build using **npm run build.aot** command then above errors was came

pls help me to solve this.
