### ISSUE TITLE
Not working with angular2.beta.14

### ISSUE THREAD

**Issue by tsukhu** [flauc/angular2-notifications#19]
I followed the steps provided , but I get a runtime error as soon as I include the NotificaitonsService 
import {NotificationsService} from 'angular2-notifications/components';

![simplenot](https://cloud.githubusercontent.com/assets/846306/14526810/9f032126-0263-11e6-8567-4fa3f99b2725.PNG)

Do let me know what could the issue here

**Comment by flauc** [comment]
Hi, i haven't updated the library to the latest angular version. But i'll try today. I'll let you know what i find.

**Comment by michalstepien** [comment]
It works with beta 15

**Comment by tsukhu** [comment]
great !! .. I have moved to Webpack now instead of SystemJS and will try it out later. Closing this issue ..
