### ISSUE TITLE
"Failed to load resource" error in 0.5.6 - 0.7.3 loading with systemJS

### ISSUE THREAD

**Issue by bomberblue07** [flauc/angular2-notifications#190]
Reverting to 0.5.3 works for me.  I load this file in systemJS:

`'angular2-notifications': {
                main: './dist/index.js',
                defaultExtension: 'js'
}`

Which I had to change from the file mentioned in the README since upgrading to 0.5.3 (maybe you should update the README?)

**Comment by flauc** [comment]
Hi @bomberblue07,

You're right thanks 👍 

In regard to the issue you have with 0.5.6 can you please paste the error message?

**Comment by bomberblue07** [comment]
Hi @flauc ,

Attached is a screenshot of my chrome error console when I try to load my app
![error](https://cloud.githubusercontent.com/assets/20325268/25023453/f3b35056-2067-11e7-9fa0-5fab489d004b.gif)

**Comment by thedukey42** [comment]
I'm getting this same error, is there a fix for this that I've missed from looking through the help documents?

Thanks!

**Comment by Niflou** [comment]
Hi !

Same error here (0.5.7), and rollback to 0.5.3 also works for me.

**Comment by bomberblue07** [comment]
@flauc This is still a problem with 0.6.0

**Comment by bomberblue07** [comment]
@flauc don't mean to be a bother, but in 0.7.2, this still isn't fixed. I'd like to be able to use the latest version of this great library soon!

**Comment by sanjay13Kumar** [comment]
On migrating to 0.5.3 I am getting error that Export is not defined in page index.js. Check it please.

**Comment by bomberblue07** [comment]
@flauc Any updates on this? Is there a fix coming? Or do those of us using SystemJS have to do some kind of workaround to get this to work?

**Comment by linuradu** [comment]
I have the following issue:
![image](https://user-images.githubusercontent.com/8996916/26869059-b88686a6-4b73-11e7-9dcd-0c94dde820a1.png)

> Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
> 	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
> 	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1393:29) [<root>]
> 	Error loading http://localhost:3000/traceur
> 	Unable to load transpiler to transpile http://localhost:3000/node_modules/angular2-notifications/dist/index.js
> 	Error loading http://localhost:3000/node_modules/angular2-notifications/dist/index.js as "angular2-notifications" from http://localhost:3000/app/app.module.js
> 	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1393:29) [<root>]
> 	Error loading http://localhost:3000/traceur
> 	Unable to load transpiler to transpile http://localhost:3000/node_modules/angular2-notifications/dist/index.js
> 	Error loading http://localhost:3000/node_modules/angular2-notifications/dist/index.js as "angular2-notifications" from http://localhost:3000/app/app.module.js

And did the following settings:
package.json
`"@angular/animations": "4.1.0",`
`"@angular/common": "4.1.0",`
`"@angular/compiler": "4.1.0",`
`"@angular/compiler-cli": "4.1.0",`
`"@angular/core": "4.1.0",`
`"angular2-notifications": "0.7.4",`

app.module.ts
> import { SimpleNotificationsModule } from 'angular2-notifications'

> imports: [
>     BrowserModule,
>     BrowserAnimationsModule,
>     SimpleNotificationsModule.forRoot(),
>   ]

system.config.js

>  map: {
>     'angular2-notifications': 'node_modules/angular2-notifications'
>  }
> packages: {
>     'angular2-notifications': { main: './dist/index.js', defaultExtension: 'js' }
> }

Could someone help me?
when I comment the line 
> imports: [
>     //SimpleNotificationsModule.forRoot(),
>   ]
is working fine. I could not get Up and running this component.

**Comment by bomberblue07** [comment]
@linuradu Currently, the only workaround seems to be to fall back to 0.5.3... or don't use systemJS :)

**Comment by bomberblue07** [comment]
Fixed in 0.7.6!
