### ISSUE TITLE
Angular-cli 1.0 no longer compiles when using angular2-notifications

### ISSUE THREAD

**Issue by maxbellec** [flauc/angular2-notifications#191]
After upgrading to angular-cli 1.0 and angular 4.0.1., I cannot compile my project with aot anymore. 

I am getting an `ERROR in vendor.d5ea40e22ccb8360dd8f.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (SimpleNotificationsComponent) [vendor.d5ea40e22ccb8360dd8f.bundle.js:31531,4]`. 

Not sure if this is related to angular2-notifications or a bug in angular-cli itself, but I only get an error with SimpleNotificationsComponent. I don't know how to trace the error.

**Comment by Nasicus** [comment]
Is already fixed see => #183

**Comment by maxbellec** [comment]
thanks @Nasicus, and sorry I had not seen the issue. It does work
