### ISSUE TITLE
@angular/language-service throws an error - private member used in template

### ISSUE THREAD

**Issue by dojchek** [flauc/angular2-notifications#192]
Running on 
```
node: 7.4.0
os: win32 x64
@angular/cli: 1.0.0
@angular/language-service: 4.0.2
@angular: 4.0.2
angular2-notifications": "^0.5.6
```
I get the following error (logged by angular/language-service):
`Error:(84, 77) Angular: Identifier 'safeSvg' refers to a private member of the component`

The fix should be as simple as changing the safeSvg modifier from private -> public

**Comment by flauc** [comment]
Yes, thanks for reporting it, I'll push a fix later today 👍

**Comment by dojchek** [comment]
Great! Quick as always :)
I can also make PR, if you don't want to bother with it - change is trivial.

**Comment by flauc** [comment]
Would you please, I won't be at my pc for a few more hours.

**Comment by dojchek** [comment]
@flauc 
Sorry, I was away in the meantime.. 
Thank you very much for fixing this one - The last issue I had for migrating to ng4 :)
