### ISSUE TITLE
How close a push notification.

### ISSUE THREAD

**Issue by nicolasq92** [flauc/angular2-notifications#194]
I want to close the push notification when I click on the notification.

If can tell me which events I should call run this, it would be a great help.

 Thanks in advance.

**Comment by wzfjesun** [comment]
you can do like this:


this._push.create('Test', {body: 'something'}).subscribe(
    res => setTimeout(() => res.notification.close(), 2000),    
    err => console.log(err)
 )

**Comment by flauc** [comment]
If you have any other issues with ng-push please open it here: 

https://github.com/flauc/ng-push
