### ISSUE TITLE
How to add simple link in the content of notification?

### ISSUE THREAD

**Issue by blackholegalaxy** [flauc/angular2-notifications#198]
Simple question here. I would like to place a link in the content of the notification. I want to use it within the info notification. 

Here is my code:

`this.notificationService.info('New task available', 'New tasks are available. <a href="">Click here</a>');`

But as you can guess it doesn't work. I saw on live demo and on documentation a `.html()` exists but nothing shows up (on live demo neither). What is then the correct html to enter to obtain a notification with html?

**Comment by flauc** [comment]
Hi @blackholegalaxy 

If you look at the example and try to create a html notification. You should see in the bottom right of the page a notification gets created. If you inspect it, you should see any content you added is in there. 

In your case, if you inspect the notification, do you get the `<a href="">Click here</a>` element? If you do, then you just need to give it a style and should be good to go.

**Comment by blackholegalaxy** [comment]
So it's not possible to use standard `.info()` and place HTML tag in it directly? Because restyling the whole notification to match the `.info()` one is... not handy.

**Comment by victornoel** [comment]
I think #218 would solve your problem @blackholegalaxy

**Comment by flauc** [comment]
It's now possible to simply pass in HTML content to both the title and content arguments.
