### ISSUE TITLE
options

### ISSUE THREAD

**Issue by chrismcgregor** [flauc/angular2-notifications#20]
It appears that lastOnBottom and maxStacks are not working correctly, both properties are always set to the default irrespective of what I set them to.

Great library!

**Comment by flauc** [comment]
Hello, thanks for the compliment :)

Are you sure they aren't working? Could you provide a code sample please?
Because i'm testing them locally and they seam to be working. For starters it's not maxStacks it's maxStack. 

You can check out the example folder and play around with the options on line 60 of the app.ts file.

**Comment by chrismcgregor** [comment]
Filip.

Thank you for your response! I changes maxStacks to maxStack and looks like everything is working perfectly including lastOnBottom.

Is it possible to have the notification appear at the top center of the browser?

Cheers!
Chris
--
Christopher McGregor
415.624.6261 // chris@mcgregor.io

**Comment by flauc** [comment]
Yes it is. All you have to do is style the simple-notification-wrapper class. 

It's located in the src/simpleNotifications.component.ts file.

But you can also just add the style to you'r css, in that case you need to include the !important verb. For example this would place them at the top center 20px from the top. 

```css
.simple-notification-wrapper {
    top: 20px !important;
    left: 0 !important;
    right: 0 !important;
    bottom: 0 !important;
    margin: auto !important;
}
```

**Comment by chrismcgregor** [comment]
Thank you!

**Comment by flauc** [comment]
It's  no problem :+1:

**Comment by chrismcgregor** [comment]
Filip,

I added the following in my css and everything worked great:

.simple-notification-wrapper {
  top: 20px !important;
  left: 0 !important;
  right: 0 !important;
  bottom: 0 !important;
  margin: auto !important;
}
I need to add display:none by default and have your library change the display attribute when needed.
.simple-notification-wrapper {
  top: 20px !important;
  left: 0 !important;
  right: 0 !important;
  bottom: 0 !important;
  margin: auto !important;
  display: none;
}
Is there a simple way do this?

Cheers!
Chris
--
Christopher McGregor
415.624.6261 // chris@mcgregor.io

**Comment by flauc** [comment]
Hi, 

I'm not really sure about what you are trying to achieve but this might be it:

##### CSS
```css

.simple-notification-wrapper {
  display: none;
}

.active {
  display: block;
}
```
##### HTML
```html
<simple-notifications [class.active]="isActive">
```
##### JS
```js
public isActive = false;
```

Then when you want it to have the display: block style just set the isActive variable to true somewhere in your code.

**Comment by chrismcgregor** [comment]
Thank you!
