### ISSUE TITLE
Icon of warn seems truncated

### ISSUE THREAD

**Issue by blackholegalaxy** [flauc/angular2-notifications#203]
Hi @flauc, since modifications about warn service, using this method produces a truncated icon. Any idea on how to fix it?

![image](https://cloud.githubusercontent.com/assets/11064123/25658318/3fc1f2be-2fd0-11e7-822f-d2f82dc66bfe.png)

**Comment by marlomgirardi** [comment]
[See this PR](https://github.com/flauc/angular2-notifications/pull/204)  :+1:

**Comment by blackholegalaxy** [comment]
Thanks. Should to the work
