### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/animations'

### ISSUE THREAD

**Issue by msiddiqi** [flauc/angular2-notifications#209]
I keep getting this error when running my app. Can someone please help?

ERROR in ./~/angular2-notifications/dist/src/simple-notifications/components/notification.component.js
Module not found: Error: Can't resolve '@angular/animations' in '/Users/muhammadsiddiqi/Documents/code/angular2/my-notifications-app/node_modules/angular2-notifications/dist/src/simple-notifications/components'
 @ ./~/angular2-notifications/dist/src/simple-notifications/components/notification.component.js 11:0-81
 @ ./~/angular2-notifications/dist/src/simple-notifications.module.js
 @ ./~/angular2-notifications/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

BTW, installing the package has some unmet dependencies too. 

npm uninstall --save angular2-notifications
- angular2-notifications@0.7.3 node_modules/angular2-notifications
npm WARN @angular/tsc-wrapped@4.1.1 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.
npm WARN @ngtools/webpack@1.2.10 requires a peer of @angular/tsc-wrapped@^0.5.0 but none was installed.
Muhammads-MacBook-Pro:my-notifications-app muhammadsiddiqi$ npm install --save angular2-notifications
my-notifications-app@0.0.0 /Users/muhammadsiddiqi/Documents/code/angular2/my-notifications-app
├── UNMET PEER DEPENDENCY @angular/animations@^4.0.1
├── UNMET PEER DEPENDENCY @angular/common@2.4.10 invalid
├── UNMET DEPENDENCY @angular/core@^4.1.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.4.10 invalid
└── angular2-notifications@0.7.3 

npm WARN @angular/tsc-wrapped@4.1.1 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.
npm WARN @ngtools/webpack@1.2.10 requires a peer of @angular/tsc-wrapped@^0.5.0 but none was installed.
npm WARN angular2-notifications@0.7.3 requires a peer of @angular/core@^4.0.1 but none was installed.
npm WARN angular2-notifications@0.7.3 requires a peer of @angular/common@^4.0.1 but none was installed.
npm WARN angular2-notifications@0.7.3 requires a peer of @angular/platform-browser@^4.0.0 but none was installed.
npm WARN angular2-notifications@0.7.3 requires a peer of @angular/animations@^4.0.1 but none was installed.

**Comment by tilowestermann** [comment]
You need to install @angular/animations: `npm install @angular/animations --save`

**Comment by kejtizuki** [comment]
Could you please show how the module file should look? I have a problem with animations.

**Comment by Jamunadevi-Vijayan** [comment]
I am using the below angular version, 
**_"@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1"_**

When i give "npm install --save angular2-notifications" , it gives error
**_ERROR in node_modules/angular2-notifications/src/simple-notificati
ons/components/notification.component.ts (2,58): Cannot find module '@angular/an
imations'._**

When i do **_npm install @angular/animations --save_**, getting error as

**_+-- @angular/animations@4.3.3
+-- UNMET PEER DEPENDENCY @angular/common@2.4.10
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.10
+-- UNMET PEER DEPENDENCY @angular/core@2.4.10
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.4.10
`-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.4.10_**
and

ERROR in node_modules/@angular/animations/src/animation_metadata.d
.ts (81,33): Initializers are not allowed in ambient contexts.

ERROR in node_modules/@angular/animations/src/private_export.d.ts
(9,33): Initializers are not allowed in ambient contexts.

If i try to upgrade typescript version, i am getting many errors.
Can i try installing some previous version of angular2-notifications, which will work for my code?

**Comment by bdbrown4** [comment]
Same error as Jamunadevi-Vijayan.

**Comment by alejandrobovino** [comment]
Same error.

**Comment by flauc** [comment]
I believe that with the latest release you should no longer be seeing this issue. Please reopen if you're still getting the issue.
