### ISSUE TITLE
npm module references src folder

### ISSUE THREAD

**Issue by tsukhu** [flauc/angular2-notifications#21]
I tried to use the npm module in the Webpack project and it runs into the issue of the .map files referencing the src folder. I was able to workaround with copying the src folder from github and placing it in the node_module installation of angular2-notifications. It would be great if you could fix it.

**Comment by flauc** [comment]
Will do :+1:  
I was planing on adding the src folder to the npm library with the next version.

**Comment by flauc** [comment]
I've added the src folder. I think you shouldn't be getting the issue any more.

**Comment by tsukhu** [comment]
This is fixed now - hence closing this issue
