### ISSUE TITLE
Linting issues

### ISSUE THREAD

**Issue by sfabriece** [flauc/angular2-notifications#210]
I'm experiencing linting issues:

command
`tslint -c ./tslint.json --type-check -t stylish --project ./src/tsconfig.app.json -e **/angular2-notifications/*` 

i'm getting errors in the following files:
`project/node_modules/angular2-notifications/src/push-notifications/interfaces/push-notification.type.ts`
`project/node_modules/angular2-notifications/src/simple-notifications/interfaces/notification.type.ts`

and many more

**Comment by flauc** [comment]
Hi @sfabriece, sorry for the long wait. You will not be getting this with the latest version.
