### ISSUE TITLE
Icon is missing for html notification

### ISSUE THREAD

**Issue by hakalb** [flauc/angular2-notifications#216]
When I use .html() the icon is missing. I have tried to set with override options but is is not working.
Is it suppose to be like this or is it a bug?

**Comment by kreuzerk** [comment]
It is supposed to be like that. If you look at the HTML template of the notification component you can see the following:

`
<div *ngIf="!item.html">
    .....
    <div class="icon" *ngIf="item.icon !== 'bare'" [innerHTML]="safeSvg"></div>
 </div>
 <div *ngIf="item.html" [innerHTML]="item.html">
    .....
</div>
`
The icon is only shown when you use success, error, alert, info, warn or create.

@flauc Is there a specific reason for this? If not I would love to create a PR to make this functionality work.

**Comment by flauc** [comment]
Well, the idea was for the html to be a bear notification so that the icon doesn't interfere with anything the user wanted to setup there. However, a lot of users have already pointed this out. 

What do you think should we include the icon?

**Comment by hakalb** [comment]
I really understand your point but I suggest to make the icon optional for HTML but in that case hidden by default.

**Comment by flauc** [comment]
Yes, that is the best approach.
@kreuzerk, if you have the time feel free to create a PR, thank you 👍

**Comment by kreuzerk** [comment]
This issue should be fixed with the PR above. Can we close this?

**Comment by flauc** [comment]
It's actually not released yet. I will have a release ready this weekend and will clean up the issues then. Thanks for your help 👍

**Comment by flauc** [comment]
Merged now, sorry for the long delay.
