### ISSUE TITLE
Add custom css class to via options

### ISSUE THREAD

**Issue by oeem1011** [flauc/angular2-notifications#217]
I cannot add my custom css class to the notification component. What i tried to do is:  put the style class it via options:

  public options = {
    position: ["bottom", "right"],
    timeOut: 3000,
    theClass: "myClass"
}

And myClass is in written in my component.scss. What i'm doing wrong`?

**Comment by andre-gois** [comment]
Same here

**Comment by anotida** [comment]
same here. Anyone to help

**Comment by maruthi-menlo** [comment]
same issue here also.

**Comment by hzitoun** [comment]
Encountering the same problem!

**Comment by dannyTorres** [comment]
Using the deep selector works for me.

:host /deep/ .myClass { 

}

**Comment by CHBaker** [comment]
@dannyTorres yes, But `/deep/ ` is depracated, so is `>>>` and `::ng-deep` is a temporary solution. So what will be a long term solution?

**Comment by flauc** [comment]
I am unsure what the angular way of doing this should be. We have `encapsulation: ViewEncapsulation.None,` on the components but this is a silly way of doing it. I hoped Angular would have an option of completely replacing the styleUrls property of a component, but as far as I know, this isn't possible.

**Comment by flauc** [comment]
This might be the best solution for the moment `::ng-deep`

**Comment by CHBaker** [comment]
hmm. i couldnt get this working with ::ng-deep. I think this issue should be re-opened, as this is a property specified in the docs that does not have a permanent solution. Not only are these things deprecated, they are considered a bad practice

**Comment by flauc** [comment]
I have succeeded using `::ng-deep` on this issue #255. It's a nasty solution but it the Angular team also doesn't have a good solution for it. Take a look at this article

https://hackernoon.com/the-new-angular-ng-deep-and-the-shadow-piercing-combinators-deep-and-drop-4b088dbe459

I'm afraid there is no better solution than to sit and wait for Angular to come up with a solution.

**Comment by CHBaker** [comment]
Alright. just an idea, is there a way you could add direct styles as a parameter to the notification object? For example, the user could pass in an object of custom styles, similar to the way angular animations passes a styles object?

**Comment by flauc** [comment]
Yes, however, this would only allow you to override styles of the `.simple-notification` div, not nested elements. You couldn't, for example, edit the font of the title. You would really be getting very little functionality here.

**Comment by flauc** [comment]
Passing an object like this might do the trick: 
```
{
  'base': {some styles},
  'title': {some styles},
  'contenct': {some styles}
}
```

What do you think?

**Comment by CHBaker** [comment]
I think those are good, it also might be helpful to include other common styles. I understand this UI is supposed to be extremely simple, I dont know about others, but at least for me I immediately looked to:

- change height and width to fit with my page
- add hover effects (opacity)
- and center (which you addressed in the last update)
