### ISSUE TITLE
Support angular's SafeHtml for notifications content

### ISSUE THREAD

**Issue by victornoel** [flauc/angular2-notifications#218]
Hi,

It would be great if on top of a simple string, the content (and title…) could accept a SafeHtml (see https://angular.io/docs/ts/latest/api/platform-browser/index/DomSanitizer-class.html).

This would resolve problems such as #198.

**Comment by blackholegalaxy** [comment]
+1

**Comment by jlberrocal** [comment]
i'm planning to make a PR for allow angular components, in that way we will be able to use angular directives, what you think about?

**Comment by victornoel** [comment]
Yes, that makes sense, it's even better than accepting `SafeHtml` :)

A good way of doing it could be as with md dialog: when opening a dialog ([open method](https://material.angular.io/components/dialog/api)), you can either give it a component or templateref (if you don't want to create a whole component just for a dialog).

**Comment by MaklaCof** [comment]
Did someone make any progress on this?

**Comment by flauc** [comment]
Sorry everyone for taking so long to implement this. There is a nice example in the readme on how to use it.

**Comment by victornoel** [comment]
Thanks :) the template solution is elegant!
