### ISSUE TITLE
preventLastDuplicates only checks active notifications

### ISSUE THREAD

**Issue by trognus** [flauc/angular2-notifications#22]
The description of the preventLastDuplicates flag says it prevents duplicates of the last notification shown, but it actually only prevents duplicate notifications if the last **active** notification is a duplicate. If the last notification is not active (user has dismissed or it has timed out) duplicate notifications are still shown.

**Comment by flauc** [comment]
You're right, but now i can't decide what the behavior should be? Should it prevent 2 same notifications to show on the screen at the same time, or should i prevent creating a notification equal to the last notification created. 

What do you think?

**Comment by trognus** [comment]
I would expect the latter to be far more useful. The preventDuplicates flag could be used to prevent most other cases of duplicate notifications being created, and I doubt there's a lot of cases where someone doesn't want duplicate notifications in a row to be created, but wants other duplicates to be allowed. Preventing a notification equal to the last created, though, allows an app to silence a continuous stream of duplicate notifications, which can be useful.

**Comment by flauc** [comment]
You're right. I'll modify it to fit the description. Thank you for your insight :+1:

**Comment by flauc** [comment]
I've actually kept both implementations. In the new library version the preventLastDuplicates option now excepts one of the following values: 

- false  
- "all" 
- "visible" 

So if it has the value "all" it prevents duplicates of the last notification created, but if it has the value visible it prevents duplicates of the last visible notification. 

I'll add this to the readme later today but it's already published so you can test it out if you want to.

**Comment by trognus** [comment]
That sounds great, thanks for the quick fix!
