### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by DmitrijDev** [flauc/angular2-notifications#220]
Hi to all.
Your lib is awesome, but when i try compile project with it i get critical error with next message: 

"ERROR in Error encountered resolving symbol values statically. Calling function 'SimpleNotificationsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in 'just_path', resolving symbol AppModule in 'just_path'"

Angular 2 version 4.2.2

What should i do to fix it?

**Comment by StickNitro** [comment]
I too was experiencing this issue when running ng build --prod

In my case I found that the SimpleNotificationsModule was imported as below

import {SimpleNotificationsModule} from "angular2-notifications/dist";

I changed this to the following which resolved my problem

import {SimpleNotificationsModule} from "angular2-notifications";

HTH

**Comment by flauc** [comment]
The latest release resolves this issue. Please let me know if you're still seeing it.
