### ISSUE TITLE
Is it impossible to use in Service?

### ISSUE THREAD

**Issue by lar-ang** [flauc/angular2-notifications#225]
Hello.
This is good notification module.
And now I want use this in Service.
But I don't know how to insert code <simple-notifications [options]="notifyOptions"></simple-notifications>.

Is it impossible?

**Comment by AmirAliSobhGol** [comment]
You can't use this in a service, how ever you can subscribe to events that the service raises in your components, for example:
in your service:
  eventSource = new Subject();
  events = this.eventSource.asObservable();
// Call this method in your service
  emitError(event) {
    this.eventSource.next(event);
  }
and in your Component:
    service.events.subscribe(error =>
      this.notificationsService.success('test')
    );

**Comment by lar-ang** [comment]
@AmirAliSobhGol , Thanks for your response.
I am trying to use your code, it get's some error on "eventSource = new Subject();"
I think I don't understand about your code.
Can you explain more about your code (including Subject() ...)?

**Comment by AmirAliSobhGol** [comment]
@lar-ang you need to import it:
```
import { Subject } from "rxjs";
```
you can read more about this here:
https://angular.io/guide/component-interaction#parent-and-children-communicate-via-a-service

**Comment by lar-ang** [comment]
Thanks @AmirAliSobhGol .
I understand your method and I think what I want is some different.

Now I have many components that uses this angular2-notifications service.
So those components have '<simple-notifications [options]="notifyOptions"></simple-notifications>' in its html file each other.
I want only 1 service to have this code, and other components can use this to show without containing this code.

In a word, I want every components don't have this code itself.
Is it possible?
Please let me know how can I do,

**Comment by AmirAliSobhGol** [comment]
@lar-ang 
there are a few ways you can achieve that.
1- Using the same way i said and the link i provided, you put <simple-notifications [options]="notifyOptions"> in your app component. app component subscribes to the service like this:
```
  myNotifService.notifications.subscribe((type, msg)=>
    notificationsService[type](msg)
  );
```
and your other components emit the events to show notification like this:
```
this.myNotifService.emitNotification('success', 'test')
```
and your service will be like this:
2- writing a wrapper around the service methods for setting the default options (you will still need to use <simple-notifications> in every component though.
like this:
```
@Injectable()
class MyNotifService {
  notifSource = new Subject();
  notifications = this.eventSource.asObservable();
  emitNotification(type, msg) {
    this.eventSource.next(type, msg);
  }
}
```
MyNotificationService extends NotificationService {
options = {...}
success(args) {
super.success(args, options)
}
}
```

**Comment by lar-ang** [comment]
Very good answers!
This is what I want to find.
Specially, 1 and 4 are very good.
Thank you very much, @AmirAliSobhGol 

one question, 5 - creating a PR.
What is PR?

**Comment by AmirAliSobhGol** [comment]
@lar-ang PR = pull request.

**Comment by lar-ang** [comment]
@AmirAliSobhGol 
Hmm, That's what I have imagined.
Can you explain me more about 'creating a PR'?
