### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/core@4.2.3

### ISSUE THREAD

**Issue by egorowp** [flauc/angular2-notifications#229]
On installing angular2-notifications via npm to angular 4.2.3 we have:
```
+-- UNMET PEER DEPENDENCY @angular/core@4.2.3
+-- UNMET PEER DEPENDENCY @angular/router@4.2.3
```

## Current Behavior
after `npm install angular2-notifications `I see:

```
+-- UNMET PEER DEPENDENCY @angular/core@4.2.3
+-- UNMET PEER DEPENDENCY @angular/router@4.2.3
`-- angular2-notifications@0.7.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/animations@4.2.5 requires a peer of @angular/core@4.2.5 but none was installed.
npm WARN ngx-modal@0.0.29 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ngx-modal@0.0.29 requires a peer of @angular/router@^3.0.0 but none was installed.
```

## Steps to Reproduce (for bugs)
run `npm install angular2-notifications`

**Comment by jotatoledo** [comment]
Most likely your dependencies are wrong. Check that your `package.json` matches:

```
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/platform-browser": "^4.0.0"
```

**Comment by bhaskerchari** [comment]
What and when is the plan to upgrade it to 4.2.3 ?

**Comment by jotatoledo** [comment]
create a new issue

**Comment by flauc** [comment]
The newest version is now compatible with 5.0.0. Please let me know if you are still getting this issue.

**Comment by chrisowooahr** [comment]
Still getting this:
├── UNMET PEER DEPENDENCY @angular/compiler@5.0.0
├── UNMET PEER DEPENDENCY @angular/core@5.0.0

commands like:
npm install @angular/compiler-cli@5.0.0 
does not solve the problem.

**Comment by flauc** [comment]
Do you have angular 5 installed? The latest version of this library has a peer dependency for `^5.0.0`. If you are using an older version, it would be best to stick with a 0.7.x version

**Comment by chrisowooahr** [comment]
@flauc Yes, angular 5 is installed. 
The dependency error was shown as i want to install bootstrap 4.0.0-beta.2
it seems that the codelyzer ha some update problems. Is must be a version higher that 4 (for codelyzer). After three commands (in the answer i mentioned) only the codelyzer was updated and after that the installation of bootstrap works finde without any problems.
