### ISSUE TITLE
No Directive annotation found on SimpleNotificationsComponent

### ISSUE THREAD

**Issue by gaykov** [flauc/angular2-notifications#23]
I'm using webpack. In my main application component I do the following: 
```javascript
import {SimpleNotificationsComponent} from 'angular2-notifications/components';
...
@Component({
  selector: 'body',
  providers: [ FORM_PROVIDERS ],
  directives: [Sidebar, Navbar, ROUTER_DIRECTIVES, SimpleNotificationsComponent],
  styles: [require('../../scss/application.scss')],
  encapsulation: ViewEncapsulation.None,
  template: require('./core.html')
})
```

And then in browser console I see the error: `EXCEPTION: No Directive annotation found on SimpleNotificationsComponent`

I don't have any ideas of how to fix it..

**Comment by daddywoodland** [comment]
Hi @gaykov,

I was having the same problem so updated my app's version of Angular2 to match this one (2.0.0-beta.16) , updated the relevant dependencies and fixed the breaking changes as I was upgrading from Angular2 v2.0.0-beta.8.

I'm not entirely sure why the error was appearing but going through these steps got rid of it for me.

- Get the latest angular2-notifications
- Ensure your app's version of Angular2 matches angular2-notifications' version (you can either update the app's reference or angular2-notifications reference of course but I updated my app)
- Fix any broken dependencies
- Fix any breaking changes

Cheers,

**Comment by flauc** [comment]
Hi @gaykov,

Sorry for the late response, did @daddywoodland suggestion solve your problem? 

I'll be updating the library to rc-1 pretty soon so that might help as well.

**Comment by gaykov** [comment]
@flauc thank you for your response. I'm using `2.0.0-beta.13` version of angular and unfortunately I can't update it to `.16` because of some other libraries dependencies.

Waiting for the `rc-1` update. I hope it will help.

Thanks for this library!
