### ISSUE TITLE
Missing documentation for click

### ISSUE THREAD

**Issue by edriang** [flauc/angular2-notifications#230]
Hi, I nearly get disappointed when, after installing, didn't see any 'click-callback' documented on the sample page!

But when I checked the `console.log` for the result of the notificationsService I saw an `click: EventEmitter` property.

I don't know if this is accidental (because maybe you use it for the `clickToClose` behavior), but it works great!

So, please complete the doc with some example like this:
```
let toast = this.notificationsService.warn('Item deleted!', 'Click to undo...', {
    timeOut: 3000,
    showProgressBar: true,
    pauseOnHover: true,
    clickToClose: true
});
toast.click.subscribe(() => {
    revertDeleteFn();
});
```
Thanks!

**Comment by flauc** [comment]
Hi @edriang,
Yes, you're right I will add it to the documentation. 
Thanks 👍

**Comment by kreuzerk** [comment]
Can we close this issue? It should be done with https://github.com/flauc/angular2-notifications/pull/240/files
