### ISSUE TITLE
ERROR in SimpleNotificationsModule is not an NgModule

### ISSUE THREAD

**Issue by mmbassetto** [flauc/angular2-notifications#235]
When i try ng serve, he's return that:

ERROR in SimpleNotificationsModule is not an NgModule

How can i fix it?

**Comment by mmbassetto** [comment]
error in ng build --prod --aot:

ERROR in Unexpected value 'SimpleNotificationsModule in C:/Projetos/Angular/node_modules/angular2-notifications/dist/src/simple-notifications.module.d.ts' imported by the module 'PessoasModule in C:/Projetos/Angular/src/app/pessoas/pessoas.module.ts'. Please add a @NgModule annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Projetos\Angular\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

**Comment by flauc** [comment]
This should no longer be happening with the new release. Sorry for the long wait.
