### ISSUE TITLE
TypeError: this.engine.setProperty is not a function at AnimationRenderer.webpackJsonp

### ISSUE THREAD

**Issue by arsalanawan** [flauc/angular2-notifications#237]
Notifications are working fine but still, there is an error in the browser console.
I am using angular4.
public options = {
        position: ["top", "right"],
        timeOut: 5000,
        lastOnBottom: true,
    };
Please let me know if any further information is required.

NotificationComponent.ngfactory.js:87 ERROR TypeError: this.engine.setProperty is not a function
    at AnimationRenderer.webpackJsonp.../../../platform-browser/@angular/platform-browser/animations.es5.js.AnimationRenderer.setProperty (animations.es5.js:502)
    at DebugRenderer2.webpackJsonp.../../../core/@angular/core.es5.js.DebugRenderer2.setProperty (core.es5.js:13729)
    at setElementProperty (core.es5.js:9383)
    at checkAndUpdateElementValue (core.es5.js:9302)
    at checkAndUpdateElementInline (core.es5.js:9236)
    at checkAndUpdateNodeInline (core.es5.js:12323)
    at checkAndUpdateNode (core.es5.js:12269)
    at debugCheckAndUpdateNode (core.es5.js:13130)
    at debugCheckRenderNodeFn (core.es5.js:13109)
    at Object.eval [as updateRenderer] (NotificationComponent.ngfactory.js:134)
View_NotificationComponent_0 @ NotificationComponent.ngfactory.js:87
proxyClass @ compiler.es5.js:14963
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13396
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4812
(anonymous) @ core.es5.js:4683
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:141
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4683
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onLeave @ core.es5.js:3934

**Comment by mateenQureshi** [comment]
I am also facing this issue, any help would be appreciated
Thanks !

**Comment by mateenQureshi** [comment]
for reference, when i initiate the simple-notification component, then this error rises in the console, please let me know m I initializing component in invalid way or there is some error on your end ?

**Comment by adityakoundinya** [comment]
Any update on this?

**Comment by flauc** [comment]
Sorry for the wrong waits. This should be resolved in the latest release. Please let me know if you are still seeing this issue.
