### ISSUE TITLE
Universal Compatibility

### ISSUE THREAD

**Issue by anas3636** [flauc/angular2-notifications#243]
Hello All,

I'am using angular2-notifications in my application and I also need to set up a prerendering with Universal.
But I keep getting this Unexpected token import Error !

```javascript
(function (exports, require, module, __filename, __dirname) { import {Injectable, EventEmitter} from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

Is there any solution for this Please ?

**Comment by flauc** [comment]
Hi @anas3636, I'm actually using this library on all my projects and they almost always include universal. I think this isn't related to the library because I have it working with universal.

**Comment by flauc** [comment]
I'm closing for now. Please let me know if you need any assistance on it.
