### ISSUE TITLE
Inconsistency between Docs and Interface for Options.preventDuplicates

### ISSUE THREAD

**Issue by ShinDarth** [flauc/angular2-notifications#247]
This:

https://github.com/flauc/angular2-notifications/blob/master/docs/toastNotifications.md#options

is saying that `preventDuplicates` is a `boolean` which defaults to `false`.

This however states that `preventDuplicates` is a `number`:

https://github.com/flauc/angular2-notifications/blob/master/src/simple-notifications/interfaces/options.type.ts#L11

**Comment by flauc** [comment]
This is fixed now. Thank you @ivanryuu  for fixing it and @ShinDarth for pointing it out 👍
