### ISSUE TITLE
add padding to icons if no content was defined

### ISSUE THREAD

**Issue by WuglyakBolgoink** [flauc/angular2-notifications#251]
HI, is it possible to add some padding to icons if no content was defined?

**Good:**
![bildschirmfoto 2017-10-08 um 19 12 29](https://user-images.githubusercontent.com/2271337/31319055-b79b86ca-ac5c-11e7-97f5-50131e8db3d2.png)

**Bad:**
![bildschirmfoto 2017-10-08 um 19 12 14](https://user-images.githubusercontent.com/2271337/31319053-b247069a-ac5c-11e7-9668-9209eb5a55d1.png)

**Comment by flauc** [comment]
Hi @WuglyakBolgoink ,

Thank you for pointing this out I'm sorry it took so long to resolve.
