### ISSUE TITLE
build aot error

### ISSUE THREAD

**Issue by werts** [flauc/angular2-notifications#256]
hi, it's really a wonderful lib,thx,but something wrong occured when built with aot.
`13% building modules 26/224 modules 198 active ...st\src\simple-notifications.module.jsError`
it seems that the error come from this lib.when i go over all issues, i still cant get any help.

**Comment by flauc** [comment]
I think that on the latest version with the new build flow this issue should not be happening anymore. Please reopen the issue if you are still seeing it.
