### ISSUE TITLE
Notification is not disappearing even after timeOut

### ISSUE THREAD

**Issue by Shahzaib631** [flauc/angular2-notifications#258]
Hi,
I'm using simple notification service to show notifications along with global setting with timeOut of 3000, But the notification doesn't go away.
I'm using it on the root component.
Thanks

**Comment by aakldey** [comment]
Got the same issue, even if I declare pauseOnHover: false, clickToClose: false in options

**Comment by aakldey** [comment]
I found solution, just need to include BrowserAnimationsModule in project modules

**Comment by flauc** [comment]
Ah, great find @aakldey thank you 👍 

It is noted in the documentation though. Closing the issue for now. @Shahzaib631 let us know if you are still seeing it.
