### ISSUE TITLE
Cannot override options ?

### ISSUE THREAD

**Issue by Niflou** [flauc/angular2-notifications#259]
Hi !

I'm trying to override the options of my notification and it does not seem to work.

The options are defined in a core components like that :
```
<simple-notifications [options]="notificationsOptions"></simple-notifications>
```
```
public notificationsOptions = {
        position: ['bottom', 'right'],
        timeOut: 5000,
        showProgressBar: true,
        pauseOnHover: true,
        clickToClose: true,
        preventDuplicates: true
    }
```
And I'm trying to override the preventDuplicates like that : 
```
this.notification.info('Info', 'Description', { preventDuplicates: false });
```

And it's not working. There is no duplicates.

Is it a known issue or am I doing something wrong ?

I searched the doc and the issues but didn't found a clue.

Thx

**Comment by flauc** [comment]
Hi @Niflou 
I'm sorry but only the following options can be overridden like that: 

id
animate
timeOut
showProgressBar
pauseOnHover
clickToClose
maxLength
theClass
icon

P.S. you can find the list in the documentation.
