### ISSUE TITLE
Notifications is not disappear in component inside router-outlet

### ISSUE THREAD

**Issue by editperson** [flauc/angular2-notifications#260]
Notifications work correctly, when I call them from basic component of lazy-loaded module. But inside my lazy-loaded module I have router-outlet, that load other components, that belong to lazy-loaded module. And when I try to call notification from this components - it doesn't work...
I would be grateful for any help in this matter.

**Comment by flauc** [comment]
Could you please create a simple example demonstrating the issue?

**Comment by xiehongyang** [comment]
yes, I just met this same problem, but I guess it doesn't belong to the component itself

**Comment by editperson** [comment]
@flauc Thank you for your feedback. Today I tried to recreate my example in plunkr for you, and I saw that the project works correctly there. The problem was that in my real application. The component in which I wanted to use your notifications expected data from the database. And in my html-template I used the data (variables), which at the time of rendering (split second) was undefined. It's generated an error and apparently blocked adequate notification's service.
Thank you again for your time.
