### ISSUE TITLE
Responsive alignment, BUG/ENHANCEMENT

### ISSUE THREAD

**Issue by CHBaker** [flauc/angular2-notifications#263]
I have tried adding an absolute position as a percentage to align the notifications in the middle of my page even if it is re-sized. but It doesn't seem to matter, I have tried setting left and margin as percentages, to no avail.
 
css:
```
:host /deep/ .extra-style {
    border-radius: 3px;
    margin-top: -9px;
    left: 29%
    width: 300px
    box-shadow: 8px 8px 10px #cacaca;
}
```

html from browser after adding `theClass: 'extra-style'`:
![screenshot from 2017-11-02 16-24-16](https://user-images.githubusercontent.com/14304935/32353254-4ac1cf18-bfea-11e7-8542-60ac8728f347.png)
for some reason, 'extra-style' is added to the parent and the child.

ps. adding the class this way is the only way i could get it working, what is a more permanent solution? see issue #217

**Comment by flauc** [comment]
This is now possible like this: 

```
options = {
  position: ['top', 'center']
}
```

The option `['middle', 'center']` is also available now so you could center the notifications both vertically and horizontally. 

Thank you for the suggestion 👍

**Comment by CHBaker** [comment]
Awesome, thanks!
