### ISSUE TITLE
Error when I run ng build --prod

### ISSUE THREAD

**Issue by UrielEscorcia** [flauc/angular2-notifications#265]
I got this error when I run `ng build --prod` 

> ERROR in Metadata version mismatch for module /Users/urisito/Documents/WORK/AppMaps/node_modules/angular2-notifications/angular2-notifications.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/urisito/Documents/WORK/AppMaps/src/app/app.module.ts, resolving symbol AppModule in /Users/urisito/Documents/WORK/AppMaps/src/app/app.module.ts, resolving symbol AppModule in /Users/urisito/Documents/WORK/AppMaps/src/app/app.module.ts

this is my app.module 

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule} from '@angular/forms';
import { HttpModule } from '@angular/http';

...
import { SimpleNotificationsModule } from 'angular2-notifications';

@NgModule({
    declarations: [
        AppComponent,
        TabListPPComponent,
        GtnProveedorComponent,
        GtnProyectoComponent,
        GtnSitioAttComponent,
        ConfirmComponent
    ],
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        MaterialM,
        AgmCoreModule.forRoot({
            apiKey: KEY_MAPS
        }),
        AngularFireModule.initializeApp(environment.firebase),
        AngularFireDatabaseModule,
        InfiniteScrollModule,
        BrowserAnimationsModule,
        SimpleNotificationsModule.forRoot()
    ],
    entryComponents: [ConfirmComponent],
    providers: [
        ProveedoresService,
        SitioService,
        ProyectoService,
        ConfirmService,
        SpinnerService
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

Versions:

> angular/cli: 1.3.2
> node: 6.11.3
> os: darwin x64

**Comment by flauc** [comment]
What version of notifications are you on? 
I think you might have to stick with a version prior to 0.9.0 if you are not using angular 5.

**Comment by UrielEscorcia** [comment]
I'm using "angular2-notifications": "^0.9.5"  with angular version 4.2.4

**Comment by flauc** [comment]
yes, I'm afraid that might not work (haven't tried it my self though). Can you try switching to a 0.7.x version or upgrading to ng5?

**Comment by UrielEscorcia** [comment]
With 0.7.0 v the build works fine, but I upgrade to ng5

**Comment by flauc** [comment]
with ng5 does the latest version not work? If so can you try and create a plunkr with the issue pls?

**Comment by UrielEscorcia** [comment]
"angular2-notifications": "^0.9.5" with ng5 works fine on `ng build --prod`.
Thank you.

**Comment by flauc** [comment]
Awesome, happy to hear it 👍

**Comment by jamilalisgandarov** [comment]
Hi, got same problem with "Angular: 4.4.6"  :/
```

  Angular: 4.4.6
  ... animations, common, compiler, compiler-cli, core, forms
  ... http, language-service, platform-browser
  ... platform-browser-dynamic, router, tsc-wrapped

  @angular/cli: 1.6.0
  @angular-devkit/build-optimizer: 0.0.35
  @angular-devkit/core: 0.0.22
  @angular-devkit/schematics: 0.0.41
  @ngtools/json-schema: 1.1.0
  @ngtools/webpack: 1.9.0
  @schematics/angular: 0.1.10
  @schematics/schematics: 0.0.10
  typescript: 2.3.4
  webpack: 3.10.0

```

tried to use it with the 0.9.5 version but got same result

   ` "angular2-notifications": "^0.9.5",
`

**Comment by flauc** [comment]
Hi @jamilalisgandarov, 

Yes, 0.9.5 will not work with 4.x.x versions of angular, can you please upgrade to 5.x.x and try it again. Or downgrade to an older version of the notifications library
