### ISSUE TITLE
Close notification by code

### ISSUE THREAD

**Issue by renetitulaer** [flauc/angular2-notifications#268]
Hi,

is it possible to close a notification by code?

I want to show the notification as long as a process is running on the server. When the process has finished it will send an event to the client and then I would like to close the notification.

**Comment by flauc** [comment]
Yes, it is. Just don't put a timeOut in the options input. All methods return an instance of the notification and it has an id property, you can use it to close the notification with the `remove(id: string)` method.

**Comment by flauc** [comment]
Please let me know if you have issues with it and feel free to repone the issue.
