### ISSUE TITLE
HTML notifications are always viewed as equal

### ISSUE THREAD

**Issue by m90smith** [flauc/angular2-notifications#27]
I'm setting 
`preventDuplicates: true,
 preventLastDuplicates: true`

But when i create two notifications that are html notifications, with different html, only the first is shown.
Taking a quick look at src/simpleNotifications.component.ts, it appears that the html property is not used when seeing if two notifications are equal.

**Comment by flauc** [comment]
You're right i have added the html notifications later on, and forgot to include them in the checking. 

Thank you for pointing it out :+1: 

I'll have it fixed shortly.

**Comment by flauc** [comment]
I think i fixed it. Thanks again :+1:

**Comment by flauc** [comment]
Also `preventLastDuplicates` accepts "all" or "visible". 

The first blocks copies  from being created even if the original isn't in the DOM any more. 

Where as "visible" only block copies if the original is still in the DOM.

**Comment by m90smith** [comment]
Great! Thanks for a fast response!
