### ISSUE TITLE
Error "metadata version mismatch" after upgrading angular2-notifications

### ISSUE THREAD

**Issue by ShinDarth** [flauc/angular2-notifications#273]
```
ERROR in Error: Metadata version mismatch for module /path/to/node_modules/angular2-notifications/angular2-notifications.d.ts, found version 4, expected 3
```

this happened after upgrading to `^0.9.5` from `^0.7.8`.

using Angular `4.4.6` with Angular CLI `1.5.0`

**Comment by flauc** [comment]
Hi @ShinDarth,

`^0.9.5` is for angular 5 if you update you will not get this error anymore. If updating isn't an option for you, the only option is to stick with `0.7.x`

Sorry, I couldn't be more helpful.

**Comment by ShinDarth** [comment]
No problem, thanks for your answer!

**Comment by aziz-haddad** [comment]
Hi @flauc  but 0.7.x is not compatible with aot right? if not is there a way to make 0.7.x aot compatible?
