### ISSUE TITLE
ERROR in Metadata version mismatch for module /angular2-notifications/angular2-notifications.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by diouf** [flauc/angular2-notifications#278]
when trying to build a release ...I got this error...

is there a recent on the definition file?

**Comment by ezeeworld-share** [comment]
Same error message here :)

**Comment by adrienlamotte** [comment]
Same error message here.
I have the problem with Angular 5 & AOT. It's working without AOT but my files are twice bigger.

Thank you !

**Comment by flauc** [comment]
Hi @diouf, @adrienlamotte 

I'm unsure how to approach this problem. I just tested the library in @angular/cli and running a production build with aot worked just fine. Could you please try to create a plunkr with the issue reproduced?

**Comment by adrienlamotte** [comment]
@flauc I am sorry, it was my mistake I was still in Angular 4 on that project... I'm upgrading several project and I lost myself... It works fine on Angular 5 ! 
So @diouf , I think you should upgrade to 5 ;-)

Thank you

**Comment by flauc** [comment]
Awesome, glad you solved it 👍 

@diouf if you are not in a position to update, I think installing version `0.7.3` should resolve it for you. Closing the issue for now.
