### ISSUE TITLE
Missing main file in package.json

### ISSUE THREAD

**Issue by peterbakonyi05** [flauc/angular2-notifications#28]
Dear Filip!

Please set the main property in the package.json file ("main": "./components.js") to be able to use it with webpack properly.

Thanks!

Awesome library by the way. :+1:

**Comment by flauc** [comment]
Hi Peter, 

I'm glad you like it :+1: 

I've added it to package.json, but i have never actually used webpack, is this change enough?  

Let me know what else i could improve.

**Comment by peterbakonyi05** [comment]
Thanks for the quick reply!

Yes this is going to be enough. Webpack will transpile my source files (and only my source files and not any code in node_modules) from TS to JS. So this:

`import { SimpleNotificationsComponent, NotificationsService } from 'angular2-notifications';`

Becomes somthing like this:

`var angular2Notifications = require('angular2-notifications');`
`var SimpleNotificationsComponent = angular2Notifications.SimpleNotificationsComponent ;`
`var NotificationsService = angular2Notifications.NotificationsService;`

After transpilation when webpack bundles my app and all the dependencies into one huge JS file it tries to resolve the module name like this

1. it looks for node_modules/angular2-notifications.js
2. it looks for node_modules/angular2-notifications/index.js
3. it looks for node_modules/angular2-notifications/ the relative path specified in package.json "main" property

Now it will find it and will be able to bundle you library as well.

Thanks again! :)

**Comment by flauc** [comment]
Its no problem, thank you for the explanation :+1:
