### ISSUE TITLE
notification service not working if i fire it from child component 

### ISSUE THREAD

**Issue by HDaghash** [flauc/angular2-notifications#281]
Hey !
notification is working fine in my app but it's not working if i fire it from child component 

any clue ?

Thanks.

**Comment by flauc** [comment]
Hi @HDaghash,
Do you have the `.forRoot()` method on the model?

**Comment by HDaghash** [comment]
yes , it was old version , updating the version include the **zone function** pull request it solved the issue 

Thanks for the fast response

**Comment by flauc** [comment]
No problem happy you solved it @HDaghash
