### ISSUE TITLE
No clickIcon EventEmitter on Notification

### ISSUE THREAD

**Issue by zrsio4** [flauc/angular2-notifications#282]
The documentation shows there should be a clickIcon event, but none exists in version 0.9.6.
There doesn't seem to be a clickIconToClose option either.

I guess I'm a little confused also, as in GitHub, the latest release is 0.9.5, but from npm, latest is 0.9.6, and the clickIcon stuff was added after 0.9.5.

**Comment by zrsio4** [comment]
My mistake. My types must've been outdated or something, as they're there now.

**Comment by zrsio4** [comment]
Sorry to close and reopen.
It looks like notification.clickIcon is never initialized with a new EventEmitter.

**Comment by yogulp** [comment]
hi zrsio,
flauc kindly updated npm 2 days ago. That's probably the reason why you can now see the clickIconToClose option.
Nevertheless, like you, i get an error subscribing the clickIcon event, as if it was not initialized.

**Comment by cosnofski** [comment]
in services/notifications.service.ts you need to add on or around line 15 the following so you don't get an npe

`notification.clickIcon = new EventEmitter<{}>();`

However, if I recall correctly, in notifications.component.ts, `onClickIcon($e: MouseEvent): void` never gets called so I replaced the icon with a button in the html template that called this method, 

And then in the notifications.components.ts I modified the method:

```
onClickIcon($e: MouseEvent): void {
    this.item.clickIcon!.emit($e);

    if (this.clickIconToClose) {
      // add the following line so onClick doesn't get called too //
      $e.stopPropagation();
      this.remove();
    }
  }
```
