### ISSUE TITLE
getting old version of angular2-notifications from npm

### ISSUE THREAD

**Issue by yogulp** [flauc/angular2-notifications#283]
Hi,

I was trying to use the recent option "clickIconToClose" when I understood that the version of the package I was using was not the last one. I currently use version 0.9.6 by installing from npm.

As you can see on this page (https://www.npmjs.com/package/angular2-notifications), the npm version was updated 2 months ago, whereas the option I am intereted in was implemented on Nov, 5

Is it possible to upgrade the package in npm catalog ?

Thanks a lot for this great angular component !

**Comment by flauc** [comment]
Thank you for pointing this out, I just published version `0.9.7`

**Comment by yogulp** [comment]
all thanks are from me !
