### ISSUE TITLE
Future request for new type of notifications

### ISSUE THREAD

**Issue by launcelot66** [flauc/angular2-notifications#287]
Is it possible to add some notify for "confirmation of user action" with buttons like "yes"/"no".

For example if user want to delete some record ask him "Do you really want to remove this record" and two buttons "Yes" and "Cancel"("No").

**Comment by jotatoledo** [comment]
why not simply use a dialog in that case?

**Comment by flauc** [comment]
Agreed, in fact I think this might be exactly what you need: 

https://github.com/Jaspero/ng-confirmations

**Comment by launcelot66** [comment]
there is some rule that rendered itself during the work with the first version of the angular - the less used third-party packages are the better way
so I was interested in the possibility of notifications with confirmation (author / styles / code - all in 1 package, so it's better, easier and more convenient)

**Comment by flauc** [comment]
I see your point, but I think it would actually prove more of a hindrance for users who only wanted a notification module. Whereas users that needed both functionalities can easily import two libraries. I'm closing this for now.
