### ISSUE TITLE
icon padding is missing in version 0.9.7

### ISSUE THREAD

**Issue by sschustar** [flauc/angular2-notifications#290]
Hello,

the layout of the notification is broken in version 0.9.7 as the icon padding is missing.

The problem seems to be in `notification.component.css`. The CSS selector for the icon padding style is `.simple-notification.has-icon .sn-content` but the class `has-icon` is missing in the DOM so the style is never applied.

Best regards

**Comment by georgique** [comment]
Confirmed.
And another thing - if I add `has-icon` class, then header `line-height` reduces to 20px, whereas it should be 30px.

**Comment by blackholegalaxy** [comment]
Since PR was merged, can this issue be closed?

**Comment by flauc** [comment]
Yes this has been resolved, thank you @georgique
