### ISSUE TITLE
Show notification + socket.io

### ISSUE THREAD

**Issue by diegobcorrea** [flauc/angular2-notifications#293]
Hi all, 

This is not a bug, but any idea how to show the notification when my server return an event socket? I use this when i do click on buttons but it doesnt work without the click.

Thank you

**Comment by flauc** [comment]
That's strange it should definitely have nothing to do with what triggered the method. 

Here is a snippet from an interceptor service for example: 

```js
 return next
      .handle(clone)
      .do(data => {
        if (
          data instanceof HttpResponse &&
          found &&
          data.status === HttpStatus.Ok
        ) {
          if (req.method !== 'GET' && found.notification) {
            this._notifications.success('Success', found.notification);
          }

          if (found.cache) {
            this.reqCache[cloneKey] = data;
          }
        }
      })
```

It's basically just invoking a success notification for any request that isn't a `GET` and is on a whitelist.

I'm closing this for now. If you still need assistance. Please reopen a new issue with a plunker demonstrating the issue.
