### ISSUE TITLE
Set global options

### ISSUE THREAD

**Issue by MurhafSousli** [flauc/angular2-notifications#297]
Hi, cool plugin!
It would nice to be able to set the options globally
```ts
SimpleNotificationsModule.forRoot({
  timeOut: 5000,
  showProgressBar: true,
  pauseOnHover: false,
  clickToClose: false,
  maxLength: 10
})
```

**Comment by flauc** [comment]
It's actually already possible, like this: 

```
<simple-notifications [options]="options"></simple-notifications>
```

But this is a great suggestion @MurhafSousli , and we're implementing it now.

**Comment by flauc** [comment]
Global options have been added. They work exactly as you describe them.

**Comment by MurhafSousli** [comment]
Great! Thanks
