### ISSUE TITLE
notifications not showing because of *ngIf directive 

### ISSUE THREAD

**Issue by Saied-Za** [flauc/angular2-notifications#298]
Consider a parent component that use routing to navigate to it's child components. to display loading when navigating , you need to do something like this in app.component.ts : 

```
import { Component } from '@angular/core';
import {
  Router,
  Event as RouterEvent,
  NavigationStart,
  NavigationEnd,
  NavigationCancel,
  NavigationError.
} from '@angular/router'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  loading = true;

  constructor(
    private router: Router) {
    router.events.subscribe((event: RouterEvent) => {
      this.navigationInterceptor(event)
    })
  }

  navigationInterceptor(event: RouterEvent): void {
    if (event instanceof NavigationStart) {
      this.loading = true
    }
    if (event instanceof NavigationEnd) {
      this.loading = false
    }
    if (event instanceof NavigationCancel) {
      this.loading = false
    }

    if (event instanceof NavigationError) {
      this.loading = false
    }
 }
}
```

And in app.component.html : 

```
 <mat-spinner *ngIf="loading"></mat-spinner>
 <router-outlet *ngIf="!loading"></router-outlet>
```

in of the child components i have to use Route Guards to check if user is logged or not.

in child.component.ts : 
```
export class ChildComponent implements OnInit {

  constructor(
    private router: Router,
    private notify : NotificationsService)
    {
      router.events.subscribe((event: RouterEvent) => {
        if (event instanceof NavigationCancel) // which will be emitted if route guard returns false
        {
          this.notifyLogin()
        }
      })
    }

    ngOnInit() {
    }

    notifyLogin()
    {
      this.notify.error("Please Log In", "you are not logged in.")
    }
}
```

When guard is checking if user is logged or not, loading spinner is activated, but when the fetching is done and spinner is disappeared , there will be no notification.

after several hours trying to fix this issue, i ended up using [hidden] directive instead of *ngIf in the app.component.html :

```
 <mat-spinner *ngIf="loading"></mat-spinner>
<span [hidden]="loading">
  <router-outlet></router-outlet>
</span>

```
but, still i rather use *ngIf directive instead of [hidden] because of its performance.
is there any way ?
and btw, thanks for this great module :)

**Comment by flauc** [comment]
I haven't come across this error yet. However, I do believe you should be able to get the notifications showing regardless of `<router-outlet></router-outlet>` if you add them to the root element. In any case, if you can setup a plunker with this issue, id be happy to help debug.

**Comment by Saied-Za** [comment]
after refactoring my code, i realized that i was creating multiple instances of <simple-notification>, deleting all instances but the one in app.component.ts, resolved the issue.
