### ISSUE TITLE
Avoid accidential styling from outside of the component

### ISSUE THREAD

**Issue by sialcasa** [flauc/angular2-notifications#3]
I have a .content selector that accidentally styles the component. You could use _ViewEncapsulation.Native_ to avoid this.

http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html

**Comment by sialcasa** [comment]
good work btw

**Comment by flauc** [comment]
Tnx for the tip i'll add it right away :+1:

**Comment by flauc** [comment]
Do you think it's enough to add it to the upper most component (NotificicationsComponent).. I'm pretty sure it should be.

**Comment by sialcasa** [comment]
I already tried it and it was enough to add it to NotificationsComponent.

BTW: for what do you use NotificationComponent? (singular- with missing s)

**Comment by flauc** [comment]
The NotificationsComponent (with the 's'). Keeps track of the notifications array, the logic behind ordering, creating and removing them where as the NotificationComponent holds all the logic for the single notification ( the timer, click to close... ).

**Comment by sialcasa** [comment]
@flauc ok - at the beginning I used the wrong class, so you should maybe think about renaming the NotificationsComponent to avoid usage mistakes
