### ISSUE TITLE
When the page is RTL based, the icon should be on other side

### ISSUE THREAD

**Issue by hope4555** [flauc/angular2-notifications#30]
When the page is RTL based, the icon should be on other side
Did not see support for RTL based pages

**Comment by flauc** [comment]
Hi Hope, 

I don't have any experience in working with RTL based pages. What is the best way to find out if a page is RTL based?

Id like to implement this feature but i'm not sure what the best way to find out if a page is RTL. 

At the moment you can always change the css of the notifications to your preferences.

**Comment by flauc** [comment]
What i could do is just ad a option for switching the notification to RTL, and just leave the logic of figuring out is the page should be RTL to the user of the library. 

What do you think about that?

**Comment by hope4555** [comment]
sounds good
this worked for me:
.simple-notification-svg{
    left:0 !important;
    right:auto !important;
}
just moving the image to the other side
![111](https://cloud.githubusercontent.com/assets/5426569/15740734/e2d73064-28be-11e6-9a54-a952632478ac.png)

**Comment by flauc** [comment]
Cool, i'll add an option later today that will do the same. 

Also, should the title and description have the `direction: rtl;` css property?

**Comment by hope4555** [comment]
I think so, yes
but i think they inherit it from the body

the only issue is with the image

**Comment by flauc** [comment]
Hi again, 

I've added the "rtl" option it aligns the icon to the left and adds the `direction: rtl` to the notification. It also fixes that padding in the content. 

Thanks for your input. Let me know if you have any other suggestions :+1:

**Comment by hope4555** [comment]
Thanks ,Working great
