### ISSUE TITLE
maxStack doesn't work

### ISSUE THREAD

**Issue by Worthy7** [flauc/angular2-notifications#300]
It just doesn't. It's always 8. regardless of how it's set.

**Comment by flauc** [comment]
That's very strange. It's working nicely for me. Are you using the latest version? Can you reproduce your issue in a plunker?

**Comment by Worthy7** [comment]
I just downloaded your latest. Sorry, my mistake, it does work ONLY for the new `forRoot` setting, but when I try to override it in a function call, it is ignored. Other properties are working fine.

**Comment by Worthy7** [comment]
```
this._notificationService.success("Name:Subject", "details",
            {
                maxStack: 2,
...

In this kind of call it is ignored, please try it.
```

**Comment by flauc** [comment]
If you look at the documentation. 

https://github.com/flauc/angular2-notifications#options

You will find this: 

> If you want a specific notification to have different options you can override them when calling any of the access methods by passing them to the override object.
The following options can be overridden:
> * id
> * animate
> * timeOut
> * showProgressBar
> * pauseOnHover
> * clickToClose
> * clickIconToClose
> * maxLength
> * theClass
> * icon

It isn't possible to override maxStack through the service, it needs to be set globally.

**Comment by Worthy7** [comment]
It seems `
<simple-notifications [options]="options"></simple-notifications>` is being ignored, I think it broke recently. Can you check it please - I tried to make a Plunkr but some bug about zone.js is making the window constantly open new tabs.

**Comment by Worthy7** [comment]
https://angular2-notifications-example-oqhtg9.stackblitz.io

^ Doesn't work

**Comment by Worthy7** [comment]
@flauc 
Bump
