### ISSUE TITLE
[FeatureRequest] Let maxStack be overwritten

### ISSUE THREAD

**Issue by Worthy7** [flauc/angular2-notifications#301]
For mobile I need to have another instance of notifications running which only allows 2 on the screen at a time instead of 8

**Comment by flauc** [comment]
It isn't possible to create a maxStack override. How would that work? Imagine it, creating one notification with max stack 2 and then another with 3. What would the max stack be? 

However, what you need is actually already possible. 

```html
<simple-notifications [options]="mobile ? mobileOptions : desktopOptions"></simple-notifications>
```

**Comment by Worthy7** [comment]
Ah, smart :) Thanks.

Obviously it wont work when resizing right.... but good enough I think

**Comment by flauc** [comment]
You should be able to listen to the resize event and change the dynamically.

**Comment by Worthy7** [comment]
@flauc  I'll give it a go, thanks
