### ISSUE TITLE
global options don't work with aot since 0.9.8

### ISSUE THREAD

**Issue by dominikg** [flauc/angular2-notifications#303]
steps to reproduce:

create a new application with angular cli 1.7.3
add angular2-notifications and setup the module in src/app/app.module.ts:
```
SimpleNotificationsModule.forRoot({
   position:['top','right']
})
```

show a notification using the service 
e.g. by adding a constructor to src/app/app.component.ts

```
  constructor(notificationsService: NotificationsService) {
    setTimeout(() => {
      notificationsService.alert('test');
    }, 500);
  }
```

add notification to src/app/app.component.html
```
<simple-notifications></simple-notifications>
```

1. start application with `ng serve` go to localhost:4200 and notice that the notification is shown in the top right corner. 
2. stop and restart with `ng serve -prod` go to localhost:4200 and notice that the notification is shown in the bottom right corner despite top being configured.

same result if options are passed via component input
```
<simple-notifications [options]="options"></simple-notifications>
``` 

output of ng -v
```
Angular CLI: 1.7.3
Node: 8.11.1
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

```

**Comment by gufigueiredo** [comment]
Any progress on this? Same problem here and no ideas on how to build for production with this issue...

**Comment by prcbass** [comment]
Please keep us updated! If this is related to #302 please note that so that someone can take it up (I could take a look) if you don't find the time. Many thanks for the continued support!

**Comment by flauc** [comment]
Thank you @prcbass 
However, I think the issue should be resolved now. Please reopen if you still see this happening in `v1.0.0`.

**Comment by evxn** [comment]
@flauc looks like overrides stopped working

**Comment by evxn** [comment]
@flauc sorry, my bad, not all options are overridable
#313
wanted to override `preventLastDuplicates`
