### ISSUE TITLE
Module build failed. simple-notifications.component.ngfactory.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by Jamizzle93** [flauc/angular2-notifications#305]
Hello,

I recently updated my project to Angular 5, but when I try to build with the angular2-notifications package I receive the following error:

> ERROR in ./node_modules/angular2-notifications/src/simple-notifications/components/simple-notifications.component.ngfactory.ts
Module build failed: Error: C:\Users\James\Documents\code\raspberry-software\web-dev\verity-portal\node_modules\angular2-notifications\src\simple-notifications\components\simple-notifications.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\James\Documents\code\raspberry-software\web-dev\verity-portal\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\Users\James\Documents\code\raspberry-software\web-dev\verity-portal\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/appeal-detail/appeal-detail.component.ngfactory.js 20:0-145
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

Any idea how to fix this? Does the library need to be packaged using the Angular Package Format (https://goo.gl/jB3GVv)?

Thanks,

James

**Comment by flauc** [comment]
Hi @Jamizzle93,

Are you using the latest version of the libarary? Are you using angular cli, if not can you please recreate the error here: https://stackblitz.com.

**Comment by Jamizzle93** [comment]
Hi @flauc 

I wasn't using the latest version. I have to update it using:

`npm install --save angular2-notifications@latest`

Now that I have done so it is all working.

Thanks!

James

**Comment by sultanramzanrana** [comment]
yhanks its working
