### ISSUE TITLE
position not workig

### ISSUE THREAD

**Issue by bsidhu009** [flauc/angular2-notifications#313]
It still showing to bottom, right 

```
 this.notify.error('This is just a title', '<p>This is just some content</p>', {
          //timeOut: 3000
          position: ["top", "left"],
          animate: 'fromTop'
        });
```

**Comment by flauc** [comment]
Only the following options can be overridden by that method. 

id
animate
timeOut
showProgressBar
pauseOnHover
clickToClose
clickIconToClose
maxLength
theClass
icon

https://github.com/flauc/angular2-notifications#options

**Comment by bsidhu009** [comment]
which method override position ?

**Comment by flauc** [comment]
You need to define it in the global settings.

**Comment by bsidhu009** [comment]
It will be great, help If you can provide blogs or other sites links.
where i can read about writing basic module writing as this one your's module

Thanks,

**Comment by iamdebodon** [comment]
Hi @flauc , can't we override the position property based on the notification type? I want to show success notification at top-right corner and warning in middle-centre.
