### ISSUE TITLE
Add "typings": "./dist/index.d.ts" to package.json file.

### ISSUE THREAD

**Issue by cealmees** [flauc/angular2-notifications#316]
Angular CLI: 1.7.4
Node: 8.9.4
OS: darwin x64
Angular: 5.2.10

There's a problem at `ng serve --aot` and  `ng build --prod` showing the 
following error: 

`Module build failed: Error: /node_modules/angular2-notifications/src/simple-notifications.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

This is solved by going to ` /node_modules/angular2-notifications/package.json`
and including `"typings": "./dist/index.d.ts"`.

Could be a way to include typings in the next release? :)

**Comment by flauc** [comment]
Thanks for the PR, next release will be later today.
