### ISSUE TITLE
Doesn't work on angular 6 (rxjs 6) (cf: screenshot)

### ISSUE THREAD

**Issue by Need-To-Learn** [flauc/angular2-notifications#319]
I just updated my angular 5 project to 6 and got this error : 

![capture](https://user-images.githubusercontent.com/23190578/39675845-42112360-5161-11e8-9390-24a1acb31964.PNG)

**Comment by flauc** [comment]
Yup, I need to update for ng 6 thanks for noticing it 👍

**Comment by flauc** [comment]
I believe `v1.0.1` should be working nicely with angular 6 now. Please let me know if it isn't working for you.

**Comment by Need-To-Learn** [comment]
Awesome, it works :) even aot !

**Comment by andriyor** [comment]
But now you require only angular 6.
When I install new packages on my project that uses angular 5 I got following warning

> npm WARN angular2-notifications@1.0.2 requires a peer of @angular/animations@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular2-notifications@1.0.2 requires a peer of @angular/c @angular/pommon@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular2-notifications@1.0.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular2-notifications@1.0.2 requires a peer of rxjs@^6.1.0 but none is installed. You must install peer dependencies yourself.
> npm WARN angular2-notifications@1.0.2 requires a peer of zone.js@^0.8.26 but none is installed. You must install peer dependencies yourself.

Please describe a minimum version of angular in peerDependencies
https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies
