### ISSUE TITLE
Karma error - NullInjectorError: No provider for options!

### ISSUE THREAD

**Issue by andrea11** [flauc/angular2-notifications#320]
Hello,
I am using `Angular 6` and update angular2-notification to `1.0.2`. My build works fine, but when I try to trigger my test, karma throw an error: 

> Error: StaticInjectorError(DynamicTestModule)[options]: 
  StaticInjectorError(Platform: core)[options]: 
    NullInjectorError: No provider for options!

As workaround a provide options as below: 

> providers: [NotificationsService, {provide: 'options', useValue: {}}]

Any idea if is it a bug and how could it be fixed?

Thank you

**Comment by Need-To-Learn** [comment]
Hi,

You have to imports SimpleNotificationModule in your TestBed, something like this:

```javascript
TestBed.configureTestingModule({
      imports: [SimpleNotificationsModule.forRoot(), BrowserAnimationsModule],
      providers: [SomeProviders],
      declarations: [ SomeComponent ]
 })
 .compileComponents();
```

**Comment by andrea11** [comment]
Hello,
You are right...

Thank you, for your answer.
