### ISSUE TITLE
Can we keep the notification if route change

### ISSUE THREAD

**Issue by webexpert4rv** [flauc/angular2-notifications#324]
@flauc My question is can we keep the notification after route changes? I want to show welcome note after login to portal.

**Comment by flauc** [comment]
Yes, that should not be a problem. You just need to make sure that the `<simple-notifications></simple-notifications>` root component is in a higher module then the routes you are changing. Placing it in the `AppComponent` for example should do the trick.

**Comment by webexpert4rv** [comment]
Thanks @flauc for saving my day. It works perfectly.

**Comment by flauc** [comment]
Happy to hear it working 👍
