### ISSUE TITLE
Progress bar not stopping the time for notification card while hovering over it

### ISSUE THREAD

**Issue by egel** [flauc/angular2-notifications#332]
As a End-User,

I want to be able to hover on a notification and read the message

so it does not disappear after I move the mouse away.

### Expected behavior
When the user will move the cursor over the message the timer for this card should be stopped. Further when the user will move the cursor away from notification card the time for this notification should be released and flow until reach `timeOut`

### Actual behavior
When the user will move the cursor over the message the timer for this card should be stopped. Further when the user will move the cursor away from notification card the time (after `timeOut`) for this notification is still running until reach `timeOut` and notification disappears.

### The Case details

Sample default notification settings

    public static notificationOptionDefaults: Options = {
      position: ["bottom", "right"],
      timeOut: 15000,
      lastOnBottom: true,
      showProgressBar: true,
      pauseOnHover: true,
      clickToClose: false,
      clickIconToClose: false,
      maxStack: 3,
      icons: {
        alert: '',
        error: '',
        info: '',
        warn: '',
        success: '',
      },
    };

### Additional Information

*   Environment(s): Angular 5
*   Browser(s): Chrome
*   OS(es): MacOSX 10.13.6
*   Occurs in (branch, version or commit): v1.0.4
*   Related to issue(s): -

### Screenshots

[default-angular-2-notification-v1.0.4.zip](https://github.com/flauc/angular2-notifications/files/2370668/default-angular-2-notification-v1.0.4.zip)

**Comment by PiotrBubel** [comment]
It was actually working like expected in previous realase of a library.

[Example with angular2-notifications version 0.9.8](https://stackblitz.com/edit/angular2-notifications-example?file=package.json) (hovering works as expected)

[Example with angular2-notifications version 2.0.0](https://stackblitz.com/edit/angular2-notifications-example-ycisrq?file=package.json) (hovering does not stop timeout)

**Comment by ddhille** [comment]
@flauc Any estimation on when this bug will be solved?

**Comment by Ashiv3r** [comment]
I've also encountered this problem on version 2.0.0. Can you give any feedback about that bug @flauc ? Regards!
