### ISSUE TITLE
Support for Angular 6.X

### ISSUE THREAD

**Issue by psnmissaka** [flauc/angular2-notifications#334]
When will you provide support for Angular 6 and beyond. Currently when i try to update one my projects to Angular 6, I get the following message since `angular-notifications-aot` is incompatible with rxjs:
```Package "angular2-notifications-aot" has an incompatible peer dependency to "rxjs" (requires "^5.5.0", would install "6.3.3").``` @flauc

**Comment by flauc** [comment]
#338 Should have solved this.
