### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by ilianiv** [flauc/angular2-notifications#338]
Hello!
Do you have plans for angular 7 support? 
When I install angular2-notification on angular 7 app I've got this issues:

```
warning " > angular2-notifications@1.0.4" has incorrect peer dependency "@angular/animations@^6.0.0".
warning " > angular2-notifications@1.0.4" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > angular2-notifications@1.0.4" has incorrect peer dependency "@angular/core@^6.0.0".
```

Greetings,

**Comment by launcelot66** [comment]
+

**Comment by flauc** [comment]
I do, thank you for pointing it out. I'm planning on updating it this weekend.

**Comment by launcelot66** [comment]
@flauc thank you for it!)

**Comment by alippai** [comment]
@flauc I didn't try out the result, but added a new PR (https://github.com/flauc/angular2-notifications/pull/339), maybe it helps :)

**Comment by PaulARoy** [comment]
Hey there, any news about this?
It's a bit blocking for a migration, I could generate a bundle and import it but if you plan to release it it's better.

(btw thanks for your awesome work !)

**Comment by gustavogialim** [comment]
Hey @flauc , any news about this issue?

**Comment by gustavogialim** [comment]
@alippai I approved of your PR. I believe everything is alright.

**Comment by flauc** [comment]
It's ready now sorry for the long wait. Big thanks to everyone for helping 👍
