### ISSUE TITLE
Notification icon hiding text in RTL mode

### ISSUE THREAD

**Issue by theunreal** [flauc/angular2-notifications#34]
![image](https://cloud.githubusercontent.com/assets/6171883/15898434/02e45666-2da1-11e6-8123-c72fb4e60bc0.png)

in RTL pages, the icon is hiding the text.

**Comment by flauc** [comment]
Did you pass the `{rtl: true}` option to the `simple-notifications` component?

**Comment by theunreal** [comment]
Yes I did.
```
public options = {
        timeOut: 5000,
        lastOnBottom: true,
        clickToClose: true,
        maxLength: 0,
        maxStack: 7,
        showProgressBar: false,
        pauseOnHover: true,
        preventDuplicates: false,
        preventLastDuplicates: "visible",
		rtl: true
    };
```

`<simple-notifications [options]="options"></simple-notifications>`

**Comment by flauc** [comment]
Can you inspect the notification and tell me if the first child of the `<simple-notification></simple-notification>` element has the `rtl-mode` class?

I've just tested the rtl option out locally and it works.
Also are you on version 0.1.57?

**Comment by theunreal** [comment]
I think I have used older version. This works now. Thanks!
