### ISSUE TITLE
Remove notification issue for those have timeout

### ISSUE THREAD

**Issue by nguyennhatthuan** [flauc/angular2-notifications#346]
Hello! I've been faced an issue about timeout for the notifications. I've checked the source code and detected that the remove() function have the argument named id for remove specific one but the code in source call remove() for remove all the notification.
In my case I have 2 types of notification: one has been set timeout, the other timeout is 0. My circumstance is that the one with timeout is 0 has been showed first (and this one need to be choose some button for disappearing) and then another notification with timeout is 2000 has been appeared. When the latter notification has been disappear by timeout, this will be remove in the stack, is it right? but the remove will clean all, so it will affect to the notification without timeout (timeout is 0) then the stack will be removed all. Is there any solution for this problem? I just want the nofication with timeout ( in case appear after the notification with timeout is 0 ) will be disappeared but still keep the former (those timeout is 0 and need to do an action for disappear). Thanks for helping me.

**Comment by flauc** [comment]
@nguyennhatthuan, if I understand correctly, you can resolve your issue by passing in the id of the notification that needs to be removed. The `remove()` method will only clear all notifications if an id isn't provided.

**Comment by nguyennhatthuan** [comment]
Yes right @flauc , for this case we need to handle call remove(id). Thanks for the reply!
