### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by FrancescoBorzi** [flauc/angular2-notifications#348]
> Package "angular2-notifications" has an incompatible peer dependency to "@angular/animations" (requires "^7.0.0", would install "8.0.0")

Also:

> Package "angular2-notifications" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.9.1").

**Comment by FrancescoBorzi** [comment]
@flauc is `angular2-notifications` going to support Angular 8 ?

**Comment by vojtechruz** [comment]
Any update on this? Angular 8 support would be great. Thanks :)

**Comment by flauc** [comment]
@FrancescoBorzi, @vojtechruz sorry for the long wait. Yes, I definitely plan on it, just hard to find the time :)

**Comment by vojtechruz** [comment]
Great to hear that, thanks a lot, appreciate it :)

**Comment by FrancescoBorzi** [comment]
thanks a lot!

**Comment by molyviatisl** [comment]
I've upgraded to Angular 8 and now I can't do a production build with Webpack 4.  I get the error "ERROR in ENOENT: no such file or directory, open '/node_modules/angular2-notifications/angular2-notifications.js'"  I guess this is related to the above issue?  Please fix soon.  I love angular2-notification and don't want to have to change it.

**Comment by Sammaye** [comment]
To be clear: this seems to be Ivy support rather than v8 support in general

**Comment by dtslvr** [comment]
`ng update @angular/cli @angular/core --force` is a workaround to override the dependency issues until this is fixed.

**Comment by borbelyzs** [comment]
Any news about this?

**Comment by straussCS** [comment]
Is this project no longer supported?

**Comment by flauc** [comment]
@straussCS it still is supported, just sadly since it's just me doing it. Maintenance is very slow.

**Comment by Sammaye** [comment]
I guess if someone has the ability to code up the solution and PR it that'd help, I would but I'm still noob with Angular and not fully savant with it yet

**Comment by FrancescoBorzi** [comment]
@flauc can you give hints about what needs to be done in order to support Angular 8 ?

**Comment by grzel4000** [comment]
Any update on this? The issue prevents us from upgrading to Angular 8. Thanks!

**Comment by romontei** [comment]
If you guys are not aware, the pull request is on tracks #356, Angular 8 compatible !

**Comment by youkouleley** [comment]
The v3.0.0 is Angular 8 compatible, see #356 for more details.
