### ISSUE TITLE
class "progress" in conflict with materializecss

### ISSUE THREAD

**Issue by cyberbobjr** [flauc/angular2-notifications#35]
Hi,
the class "progress" is in conflict with MaterializeCSS.

Css class for materializeCss :
`position: relative;
    height: 4px;
    /* display: block; */
    width: 100%;
    background-color: #acece6;
    border-radius: 2px;
    margin: 0.5rem 0 1rem 0;
    overflow: hidden;`

the progress toaster is misaligned with toaster.
maybe you should change the classname of progress widget ?

Best regards

**Comment by flauc** [comment]
Hi, 

Thanks for the info. I'll rename it in the next update :+1:

**Comment by flauc** [comment]
I've renamed .progress to .progress-loader let me know if you spot any other conflicts please.
