### ISSUE TITLE
npm registry out of date

### ISSUE THREAD

**Issue by paradox37** [flauc/angular2-notifications#357]
Latest version of this package available on npm is 2.0. I am not sure what current version is, but last publish was one year ago on npm registry but there are more recent changes here on github. Would it be possible to update npm registry?

**Comment by youkouleley** [comment]
@flauc how do you want to proceed?

**Comment by flauc** [comment]
@youkouleley thank you for pinging me. Can you give me you're npm handle so I can add you to the library?

**Comment by youkouleley** [comment]
@paradox37 I'm on it, the master branch is stable to me, but I'd like to get some feedbacks from other persons before publishing it. It looks like someone has a problem with it.
We're discussing it on a closed pull request here : #356 feel free to help by testing it on your side

**Comment by flauc** [comment]
@youkouleley I'm sorry for the delay. I've added you to npm now.

**Comment by youkouleley** [comment]
Thanks @flauc I can confirm the last commit of `master` is now published as v3.0.0

**Comment by flauc** [comment]
@youkouleley thanks for being patient with me man!

**Comment by youkouleley** [comment]
@flauc I understand that your situation has changed since when you created this library!
