### ISSUE TITLE
Custom button action in notification

### ISSUE THREAD

**Issue by theunreal** [flauc/angular2-notifications#36]
I tried the following code:

```
this._service.html('Are you sure?<br/><button md-button (click)="freeUser()">Yes</button>',"info");
```

Unfortunetly the click event not working, so my question is, if there is any way to make custom button with some action in a notification body?

**Comment by flauc** [comment]
Hi @theunreal,

I'm not sure how to implement this functionality do you maybe have a suggestion or an example library with similar functionality?

**Comment by TrevorBroderick1** [comment]
What if instead of having a button inside of the notification, the click event of the entire notification fired the function.

Could a possible solution be to chang the definition of the html method to take a delegate parameter, stating the function to execute when the notification is dismissed via click?

**Comment by flauc** [comment]
I'm working on a solution, but I've been short on time lately. Anyway the solution uses ` ViewContainerRef.createComponent()` to dynamically create the provided component in side of the notification.

With this approach you could create a component and then pass it to the notification service. The only down side is that you will have to use a service to communicate with the component. 

It would look something like this: 

```js
notificationsService.dynamic('success', MyComponent) 
```

**Comment by sandromaio** [comment]
Hi @flauc ,

Why not remove the "bypassSecurityTrustHtml", this is what's not enabling the custom html to allow button's.

This way we could have a custom notification for warning (eg. "Do you wish to remove this? <yes> | <no>".

Cheers

**Comment by yekibud** [comment]
@flauc Have you started a branch for the `dynamic` notification type?  I think I'm going to start looking into this.

**Comment by flauc** [comment]
I have a pretty good idea on how to make this. The only problem is that i think that in the current state of Angular 2 using dynamic compilation of modules breaks AoT I'm not sure if this is still the case however. 

I have done something similar here: 

https://github.com/flauc/ng2-simple-components/tree/master/src/modal

I've just added push notifications and was thinking about started working on this tomorrow.

**Comment by yekibud** [comment]
Cool.  Looking forward to what you come up with.

**Comment by trumbitta** [comment]
Hey, any update on passing a component as the body of the notification? It would really help!

**Comment by jiayihu** [comment]
> Why not remove the "bypassSecurityTrustHtml", this is not enabling the custom html to allow button's.

I'm having the same problem. Currently I can't add a button with `X` to tell the user it's dismissible, using Bootstrap [HTML for alerts](dismissible).

**Comment by hsbalar** [comment]
Hey guys, I have make working plunker example for closing an individual notification
https://plnkr.co/edit/MvjQ6F3dKMIuGz5ushFN?p=preview

**Comment by arwindgao** [comment]
@flauc i'd like to suggestion you could consider NgComponentOutlet or NgTemplateOutlet (angular > 4.x) for dynamic templates or components. I am sure they're supports AOT compiler :)

**Comment by bertrandg** [comment]
hi,
Here is an easy way to add button inside notification and bind it to an action:
demo: https://angular-j9rrgn.stackblitz.io
code: https://stackblitz.com/edit/angular-j9rrgn

And thanks @flauc for your great lib! :)

**Comment by flauc** [comment]
@bertrandg Thank you for the great example 👍
