### ISSUE TITLE
Notification is not working in Angular 9

### ISSUE THREAD

**Issue by ManikantaNani** [flauc/angular2-notifications#362]
Hi,
I am facing an issue running this library in Angular 9. Please, find the below error

**ERROR** in node_modules/angular2-notifications/lib/simple-notifications.module.d.ts:5:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (angular2-notifications) which declares SimpleNotificationsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
 export declare class SimpleNotificationsModule {
                           ~~~~~~~~~~~~~~~~~~~~~~~~~

Can anyone help to solve this issue

**Comment by Guerric-P** [comment]
Hi @ManikantaNani thank you for reporting this issue, can you paste your `package.json` so I can try to reproduce your issue in the same conditions?
