### ISSUE TITLE
Library is not working with Angular 10

### ISSUE THREAD

**Issue by fallais** [flauc/angular2-notifications#365]
I have an error.

```txt
ERROR in node_modules/angular2-notifications/index.d.ts:16:40 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

16     static forRoot(options?: Options): ModuleWithProviders;

```

Reference about the issue  : https://angular.io/guide/migration-module-with-providers

**Comment by Kumar-Aakash** [comment]
@fallais  I am using Angular version 10.0.5 and my app module only has this one import line and it is working fine.

`SimpleNotificationsModule.forRoot()`

Try running once again with this to check if the Ivy engine is enabled and if Ivy is not allowing this library to compile.

```
"angularCompilerOptions": {
    "enableIvy": false,
  }
```

**Comment by Guerric-P** [comment]
Hi @fallais are you still facing the issue? If so, can you share your `package.json` file?
