### ISSUE TITLE
Does it work with Angular 11?

### ISSUE THREAD

**Issue by maerni** [flauc/angular2-notifications#369]
We just created a new project with Angular 11 and installed angular2-notifications.

Now we have the following warnings:

npm WARN angular2-notifications@9.0.0 requires a peer of @angular/animations@^9.0.0 but none is installed.
npm WARN angular2-notifications@9.0.0 requires a peer of @angular/common@^9.0.0 but none is installed.
npm WARN angular2-notifications@9.0.0 requires a peer of @angular/core@^9.0.0 but none is installed.
npm WARN angular2-notifications@9.0.0 requires a peer of @angular/platform-browser@^9.0.0 but none is installed.
npm WARN angular2-notifications@9.0.0 requires a peer of @angular/platform-browser-dynamic@^9.0.0 but none is installed. 

Can we ignore them? Or does this library only works with Angular 9? If yes, when it will work with Angular 11?

Thanks very much.

Best regards
Mike

**Comment by Guerric-P** [comment]
Hi, I've not tested the library in Angular 11 yet, but I know that these warnings can usually be ignored in previous versions. When I have some spare time I'll do the upgrade, feel free to propose a PR if you want to contribute.

**Comment by maerni** [comment]
Hi

I'm a newbie to Angular so I don't trust myself to do a PR.

But I hope that the library will officially run with Angular 11 soon ;-) 

Thank you very much.

**Comment by Disane87** [comment]
We can confirm its working with Angular 11 but a native support would be prefered

**Comment by PowerKiKi** [comment]
@Guerric-P a PR now exist to solve this, would you have time to merge it ? https://github.com/flauc/angular2-notifications/pull/371

**Comment by flauc** [comment]
Thanks everyone!
