### ISSUE TITLE
Document reuse

### ISSUE THREAD

**Issue by et1975** [flauc/angular2-notifications#38]
I can't seem to get notifications working unless the directive is included in the template of the component that does the notification. What I'd like to do is have the directive in my main/app component and only inject the service into the individual components that produce the notifications, therefore reusing the same "toaster". Is it possible?

**Comment by flauc** [comment]
Hey, 

Yes it's possible i don't know why you can't get it to work. 

Try to place the directive in to the `AppComponent` for example and register the provider for the service there as well. Then you should be good to go.

**Comment by et1975** [comment]
Ok, that was a angular2 noob situation: directive and provider should only be declared as dependency of the main/app component. Works as advertised!
