### ISSUE TITLE
Angular 11 version

### ISSUE THREAD

**Issue by pelord** [flauc/angular2-notifications#380]
I try to install angular2-notification in my project based on angular/common 11.2.14.

I install your project this way from my dependencies

`"angular2-notifications": "git+https://github.com/flauc/angular2-notifications.git",
`
I get :>

npm ERR!   @angular/compiler@"^11.2.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"~11.0.5" from angular2-notifications@11.0.0

Someon know how to solve it? I have also tried to update to angular 12 but I still have an issue with your lib!

Thanks for your support

**Comment by pelord** [comment]
Solved my migration the project to angular 12. 

@flauc Any plan to release the project on npm?

**Comment by bjuergens** [comment]
i have the same problem. How did you install so that it works with angular12? I.e. when I do the old `npm i --save git+https://github.com/flauc/angular2-notifications.git`, it only installs metadata, but no js/ts files. So `ng update` works, but compilation does not.

**Comment by Guerric-P** [comment]
The library is now released as v12.0.0
