### ISSUE TITLE
issue with lazy loaded module in angular 13

### ISSUE THREAD

**Issue by cavone-leonardo** [flauc/angular2-notifications#392]
Use Case

I reproduced the problem in this [example](https://stackblitz.com/edit/angular-ivy-kshwpm):

Description

Using angular2-notifications version 12 in a lazy loaded module, you get the following error:

ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

Angular v. 13.2.5

![image](https://user-images.githubusercontent.com/67264683/156526998-3e207852-16fe-4a63-bc2b-857397d5cf8f.png)

**Comment by Nomis87** [comment]
Same for me with Angular 12

**Comment by wwjhu** [comment]
Any chance you can create a 12.0.1 release with this fix any time soon?

**Comment by maychan111** [comment]
Same issue here.

@flauc can we have a 12.0.1 release please?

@wwjhu how are you getting around this issue with no 12.0.1?

**Comment by wwjhu** [comment]
> @wwjhu how are you getting around this issue with no 12.0.1?

I created a private fork that I hope to get rid of once a release is here.
