### ISSUE TITLE
TypeError: el.createShadowRoot is not a function

### ISSUE THREAD

**Issue by Fenkiou** [flauc/angular2-notifications#4]
Hi,

I'm trying to use your plugin in an Ionic 2 app.

Unfortunately, I get a `TypeError: el.createShadowRoot is not a function`

I searched on this and found [this link](http://stackoverflow.com/questions/34824758/angular2-exception-typeerror-el-createshadowroot-is-not-a-function-safari-edge) that talk about `EncapsulationView`and I saw that you recently introduce this in your code.

So I tried to use it for my @Page component but same thing happened.

If I remove the `directives: [NotificationsComponent]` the error disappears but the notifications don't work.

So I'm not sure if the issue is related to this library or the ionic framework..

PS :
In the readme, it says `directives: [NotificationComponent]` and in sample it's `directives: [NotificationsComponent]` so it could be helpful to rename the class as @sialcasa suggested.

**UPDATE :**
With `ViewEncapsulation.Native`, I get a blank page with previous error in Firefox and Safari. For Chrome, my page is displayed with broken CSS  and I get a `TypeError: Cannot convert undefined or null to object in [ {{ "pick_photo_button" | translate }}`.
With `ViewEncapsulation.Emulated`, all 3 browsers displays the previous Chrome behavior.

So apparently, there is a conflict with ng2-translate plugin too.

Not sure if it's all clear..

**Comment by flauc** [comment]
As you know i'we added the ViewEncapsulation recently and didn't have a chance to test it. It's just one of thous things that i'm hopping will get smooth out with the new beta releases of angular. 

As for the NotificationsComponent i'll rename it right away. You're completely right it's confusing.

**Comment by flauc** [comment]
I removed the ViewEncapsulation, for now. Because it seams to be working only in chrome. But with ViewEncapsulation removed it now works in both firefox and safari.

**Comment by Fenkiou** [comment]
Thank you for this. The error is gone now.

Now I'm looking at why my CSS is broken.

**Comment by flauc** [comment]
You might have some conflicts with your css and the library css. Since there is no ViewEncapsulation they might overlap. I'll add simple-notifications prefix to all of the libraries css.

**Comment by Fenkiou** [comment]
Nope sorry it was on me...

I used this `<simple-notifications></simple-notifications>` instead of this `<simple-notifications [options]="options"></simple-notifications>` and didn't put any options in my @Page..

I thought it was possible to use it like this with just :
`this.notificationsService.success('title', 'message', options)`

It's all good now.

**Comment by flauc** [comment]
It's no problem. Glad you made it work :+1:

**Comment by sialcasa** [comment]
@flauc ViewEncapsulation.Native uses native Shadow Dom API that isn't supported by other browsers then chrome yet. But there is a polyfill for it: http://webcomponents.org/polyfills/

**Comment by flauc** [comment]
Yes but i want to keep the library lightweight with as little dependencies as possible.

**Comment by sialcasa** [comment]
Ah - I saw you prefixed your CSS classes - this is a good solution!
