### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by dc-p8** [flauc/angular2-notifications#414]
We can't use this package in moderns Angular architectures (standalone app root component)  due to the fact that BrowserModule is imported in SimpleNotificationsModule.

The problem is already fixed by https://github.com/flauc/angular2-notifications/pull/396

I tried to find a workaround for hours but now I'm stuck and forced to copy this lib in private repos, we can only wait for a release to come.

Please make a release.

**Comment by sengmann** [comment]
We are also stuck with the same problem

**Comment by Guerric-P** [comment]
Created a 16.0.1 release
