### ISSUE TITLE
NotificationsService should return the generated ID of a message

### ISSUE THREAD

**Issue by kleferbe** [flauc/angular2-notifications#42]
Hi,

first let me thank you for all your work! It works really nice.

I would like to create a sticky notification (when my app gets disconnected) that i remove later (when it gets reconnected).
The `NotificationsService.remove(id:string)` method does allow me to remove the notification. But it does neither allow me to specify the id of a notification (f.e. in the overrides) nor does it return the created id of the notification.

I see that i can subscribe to the `onCreate` event of the `SimpleNotificationsComponent` to receive the id of the created notification,  but the `SimpleNotificationsComponent` is far away in my root component. It is the `NotificationsService` that i want to interact with. It would make its interface more consistent.

My suggestion would be

1. Move the id generation code to the `NotificationsService` and return the generated id from `.error()`, `.alert()`,...
2. Allow us to supply a custom id. How about an id attribute in the overrides?

Either of both suggestions would support my usecase.

Bernhard

**Comment by flauc** [comment]
Hi @kleferbe,

Thank you for the input, i'm really short on time at the moment, but i'll look in to it and try to implement something as soon as possible.

**Comment by flauc** [comment]
Hi again @kleferbe,

I've implemented the changes you've suggested. Sorry i couldn't do it earlier.

Thanks for the help :+1:

**Comment by kleferbe** [comment]
Works like a charm!

Great, that you could implement it so soon! Thank you very much!

**Comment by flauc** [comment]
It was no problem,

Please let me know if you have any other ideas.
