### ISSUE TITLE
Migration Angular 16

### ISSUE THREAD

**Issue by sc-mickael** [flauc/angular2-notifications#421]
Hi,

Angular 16 need an update of Zone.js. : https://update.angular.io/?v=15.0-16.0
`Make sure that you are using a supported version of Zone.js before you upgrade your application. Angular v16 supports Zone.js version 0.13.x or later.`

But angular2-notifications uses zone.js@"^0.11.4"

Is a migration planned ?

Thanks a lot

**Comment by Guerric-P** [comment]
Closed by #423
