### ISSUE TITLE
angular2 cli with notifiction

### ISSUE THREAD

**Issue by venkatesh707** [flauc/angular2-notifications#45]
Hi Flauc,
Could you please advise me on, how to use notification in angular2 cli (rc4)..I am new to angular2..Please give me your guidance step by step that i can easily under stand..

Thanks and Regards
Venkatesh

**Comment by flauc** [comment]
Hi @venkatesh707 sorry i couldn't respond earlier. 
 
There is a great explanation how to do this here #25.

Check out the last few comments,

**Comment by itamark** [comment]
Wait, @flauc  - how can it work in rc4 if it requires the use of @NgModule?

**Comment by flauc** [comment]
Hi @itamark i've updated to @NgModule in the latest release. At this point i don't think you can use the library on a version older then rc5, but you can always clone or install an earlier version from npm.

**Comment by flauc** [comment]
Actually i'm wrong you can still use the library in older versions of Angular 2. If you look at `component.js˛` services and components are still exported individually so you can register the providers and directives with out using @NgModule
