### ISSUE TITLE
exports is not defined 

### ISSUE THREAD

**Issue by AJMalik007** [flauc/angular2-notifications#46]
I am using this lib in my app but its not working is shows this error
`exports is not defined `
how can I fix it? I have no clue about it. 
I am using Angular 2 rc-4

**Comment by flauc** [comment]
I really don't know. Are you using system.js or webpack?

**Comment by AJMalik007** [comment]
system.js

**Comment by flauc** [comment]
Are you only getting the error when you import the notifications? Can you send me your system config?

**Comment by AJMalik007** [comment]
`/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    // map tells the System loader where to look for things
    var map = {
        'app': '/app', // 'dist',
        '@angular': '/node_modules/@angular',
        'angular2-in-memory-web-api': '/node_modules/angular2-in-memory-web-api',
        'rxjs': '/node_modules/rxjs'
    'notifications': 'node_modules/angular2-notifications'
    };
    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' },
        'notifications': { main: 'components.js', defaultExtension: 'js' }
    };
    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'forms',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'router',
      'router-deprecated',
      'upgrade',
    ];
    // Individual files (~300 requests):
    function packIndex(pkgName) {
        packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }
    // Bundled (~40 requests):
    function packUmd(pkgName) {
        packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }
    // Most environments should use UMD; some (Karma) need the individual index files
    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    // Add package entries for angular packages
    ngPackageNames.forEach(setPackageConfig);
    packages['@angular/router'] = { main: 'index.js', defaultExtension: 'js' };
    var config = {
        map: map,
        packages: packages
    };
    System.config(config);
})(this);
`

**Comment by flauc** [comment]
It seams like you've done everything right here. Are you sure it only happens when you import notifications?

Are you compiling to systemjs or commonjs?

**Comment by AJMalik007** [comment]
Yes I am compiling it

**Comment by flauc** [comment]
In your tsconfig file are you using systemjs or commonjs as the module 

```js
"module": "commonjs",
```

**Comment by AJMalik007** [comment]
yes i am using commonjs

**Comment by flauc** [comment]
I really don't know what the issue might be then. If the project is on github you can send me the link and i'll take a look.
