### ISSUE TITLE
NotificationsService only available on children, not throug router-outlet

### ISSUE THREAD

**Issue by demil133** [flauc/angular2-notifications#47]
Other services are working properly. I don't know if this may be a RC4 feature/bug or something related to implementation. I could perfectly declare it in every routed component, however I don't think this is the way the package was intended to be used.

What I do, even if declaring a service globally is discouraged by the official documentation) is:

   *Declare* the componen and inject service on your main Component
```ts
import {NotificationsService, SimpleNotificationsComponent} from "angular2-notifications";

@Component({
    ...
    providers: [NotificationsService],
    directives: [SimpleNotificationsComponent, ...]
    template: `
            <child-component></child-component>
            <router-outlet></router-outlet>
    `,
    ...
})
export class AppComponent{
    public options = {
        timeOut: 2000,
        showProgressBar: false
    };
}

bootstrap(AppComponent, [APP_ROUTER_PROVIDERS, NotificationsService]);
```
  *Use everywhere*

It works properly with the actual Component where the `SimpleNotificationsComponent` was used, and it's children.
```ts
import {NotificationsService} from "angular2-notifications";

/**
  * This is a child component
  */
@Component({
    ...
    selector: 'child-componet',
    providers: [NotificationsService],
    ...
export class ChildComponent(){
    constructor(private ns:NotificationsService){}
    someFunction(){
        this.ns.info('title','content');
    }
}
```
However it doesn't work for routed components
```ts
import {NotificationsService} from "angular2-notifications";

/**
  * This is a routed component
  */
@Component({
    ...
    providers: [NotificationsService],
    ...
export class RoutedComponent(){
    constructor(private ns:NotificationsService){}
    someFunction(){
        this.ns.info('title','content');
    }
}
```

**Comment by demil133** [comment]
Solved it. Noob mistake:

```ts
import {NotificationsService} from "angular2-notifications";

/**
  * Every component but the App root one
  */
@Component({
    ...
    providers: [],    // does not contain NotificationsService
    ...
export class AnyOtherComponent(){
    constructor(private ns:NotificationsService){}
    someFunction(){
        this.ns.info('title','content');
    }
}```

I suppose I was overriding the instance for the components

**Comment by flauc** [comment]
> ...even if declaring a service globally is discouraged by the official documentation)
Are you sure that declaring services globally in discouraged? I think many services are intended to be used as singletons in that case it makes most sense to include them in the app.component especially if you have to use them on more places across your app. 

I went through the official examples and they register providers in the app.component even if they could be registered on a lower component. 

Also if you look at the [ngrx-example-app](https://github.com/ngrx/example-app) for example. All services are registered at root.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
