### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by sergio11** [flauc/angular2-notifications#5]
hi there,

i am finding problems at use it wit webpack

`ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular2-notifications' in C:\Us
ers\Sergio_2\auth-angular2-app
 @ multi vendor`

here is the webpack config fragment 
`entry: {
    'vendor': [
      // Polyfills
      'es6-shim',
      'es6-promise',
      'reflect-metadata',
      'zone.js/dist/zone-microtask',
      'zone.js/dist/long-stack-trace-zone',
      // Angular2
      'angular2/platform/browser',
      'angular2/platform/common_dom',
      'angular2/core',
      'angular2/router',
      'angular2/http',
      // RxJS
      'rxjs',
      // Other
      'angular2-jwt',
      'angular2-notifications'
    ],
    'app': [
      './src/index'
    ]
  }`

**Comment by flauc** [comment]
To be honest i'we only ever used system.js with my angular2 applications. But i'll have a look and let you know.

**Comment by flauc** [comment]
I've managed to make it work with webpack. It was actually quit simple. All i did was clone this repo:

[Angular2-webpack-starter](https://github.com/preboot/angular2-webpack#add-new-components-services-pipes-with-angular-2-cli) 

Installed the library
npm install angular2-notifications

And modified:

home.ts
```js
import {Component, OnInit} from 'angular2/core';
import {FORM_DIRECTIVES} from 'angular2/common';
import {SimpleNotificationsComponent, NotificationsService} from 'angular2-notifications/components'

@Component({
  selector: 'home',
  directives: [SimpleNotificationsComponent],
  pipes: [],
  styles: [require('./home.scss')],
  template: require('./home.html')
})
export class Home implements OnInit {
  constructor(private _service: NotificationsService) {}
  public options = {
    timeOut: 5000,
    lastOnBottom: true
  };

  create() {
    this._service.success('bla', 'example')
  }
}
```

bootstrap.ts 
```js
...
import {NotificationsService} from 'angular2-notifications/components'
...
  return bootstrap(App, [
    ...
    NotificationsService,
    ...
});

```

And home.html
```html
<simple-notifications [options]="options"></simple-notifications>
<button (click)="create()"></button>
```

It's all working but the css is a little broken. There might be some overlaps.

**Comment by sergio11** [comment]
thanks for response.

I will follow you suggestion with Angular2-webpack-starter.

greetings

**Comment by flauc** [comment]
np.. glad i could help.
