### ISSUE TITLE
Failed to execute 'animate' on 'Element': 'null' is not a valid value for easing

### ISSUE THREAD

**Issue by theunreal** [flauc/angular2-notifications#51]
Whenever a notification message pops up, console shows this error:
`EXCEPTION: TypeError: Failed to execute 'animate' on 'Element': 'null' is not a valid value for easing`
and the app stucks.

`showProgressBar: true` but there is no animation of progress, seem like a problem with the notification progress..

Any idea?

**Comment by flauc** [comment]
Hi @theunreal 

Can you try to recreate the error in a plunker please? The reason i ask is because i'm not getting the error locally. Also what version of the library are you using?

**Comment by theunreal** [comment]
@flauc i'm using the latest version, and I just created a new angular2-cli project and tried to use this library. https://github.com/angular/angular-cli

**Comment by theunreal** [comment]
Seem like it's angular problem https://github.com/angular/angular/issues/9752

**Comment by flauc** [comment]
Oh, i was trying it out on chrome. That's why i wasn't getting the error.

**Comment by theunreal** [comment]
This is in chrome too. Are you using latest angular2 cli with rc4?

**Comment by flauc** [comment]
I'm using rc4 but not angular2 cli. Maybe it's angular2 client related?

**Comment by purplemass** [comment]
@flauc I'm also getting this error using angular-cli with rc4 on all 0.2.x releases. No issues with 0.1.7.

Oddly enough, I'm seeing the error when I use your [demo page](http://flauc.github.io/angular2-notifications/) in Chrome but not in Firefox.

Chrome: 52.0.2743.82
Firefox: 47.0.1

**Comment by flauc** [comment]
I'm still not getting the error at all, i'm using chrome 51.

**Comment by purplemass** [comment]
@flauc please see this screen grab showing the errors on your site using Chrome 52:

![screen shot 2016-07-26 at 11 29 08](https://cloud.githubusercontent.com/assets/51887/17135147/277f0ab6-5326-11e6-9102-389044202d71.png)

I disabled all of Chrome extensions before running this test.

Hopefully the fact that the error is not there with version 0.1.7 can give us a clue as to why this is happening for some users.

**Comment by flauc** [comment]
Does it break the application for you? Do you still get the enter and leave animations? 

I updated Chrome to 52, and i still can't get the error to show.

**Comment by purplemass** [comment]
In my app: the first notification works -> the error comes up -> angular app stops working.

Same thing happens on your demo.

**Comment by flauc** [comment]
Can you send me the error you get on your application. I know it's the same error i'm interested in the line that causes the error. 

Thank you for your help :+1:

**Comment by flauc** [comment]
I've figured it out. Looks like it really is an error with Angular 2. The issue has been posted on the Angular github page [here ](https://github.com/angular/angular/issues/10245)

**Comment by flauc** [comment]
I wrote a workaround until the new version of Angular ships.

**Comment by purplemass** [comment]
That's great @flauc! Thanks very much for 1) providing this library 2) getting the workaround in place so fast

**Comment by flauc** [comment]
It's my pleasure. Let me know if you encounter any other bugs thanks :+1:

**Comment by busbina** [comment]
@flauc is the work around posted anywhere?

**Comment by flauc** [comment]
The workaround is implemented in the latest version. Are you getting the same error in the latest version?

**Comment by busbina** [comment]
Nope, I'm still on rc4, didn't think rc5 was out, i'll update. THANKS!

**Comment by flauc** [comment]
This is all it [takes](https://github.com/flauc/angular2-notifications/commit/241225dbf4427701c44e752187f0f91fe648ac45)

**Comment by busbina** [comment]
Sweet, thanks, should help others, this is the first hit when you Google the error.
