### ISSUE TITLE
console.log is left in the code

### ISSUE THREAD

**Issue by mvar** [flauc/angular2-notifications#54]
https://github.com/flauc/angular2-notifications/blob/86bd9970ce304be43a12f61035a122a5bbf20a63/src/notification.component.ts#L224

**Comment by flauc** [comment]
Thanks for pointing that out. Will remove it right away :+1:

**Comment by flauc** [comment]
I've removed the console.log and published a new release. Thanks again.

**Comment by mvar** [comment]
@flauc thanks for quick response. This library looks and works really great. Nice job.
