### ISSUE TITLE
Update to rc5

### ISSUE THREAD

**Issue by yahyaKacem** [flauc/angular2-notifications#56]
The rc5 introduces the concept of module [(@NgModule)](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html).

**Comment by flauc** [comment]
Hi @yahyaKacem, thanks for letting me now. This looks awesome, i'll update as soon as possible.

**Comment by flauc** [comment]
I've just updated to RC5 let me know if you have a chance to try it out :+1:

**Comment by yahyaKacem** [comment]
hi, thanks for your quick response, I did update to the latest version everything seems to work OK, thanks.
