### ISSUE TITLE
RTL not working in the latest version

### ISSUE THREAD

**Issue by theunreal** [flauc/angular2-notifications#57]
I added the following to the options:

`rtl: true`

but the icon appears on the left side of the notification and sometimes getting over the text. I remember this feature working in previous versions.

**Comment by flauc** [comment]
I'll have a look thanks for the heads up.

**Comment by flauc** [comment]
Hi @theunreal i've solved the padding issue, but are you sure that the icons shouldn't be on the left side of the notification? I'm not really sure what the correct approach is in RTL mode.

**Comment by theunreal** [comment]
![image](https://cloud.githubusercontent.com/assets/6171883/17707154/bef0699a-63e7-11e6-8c90-1a0916078362.png)

See attached image

**Comment by flauc** [comment]
Have you updated to 0.3.1 that should be fixed now?

**Comment by theunreal** [comment]
Works great @flauc thanks
