### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by superzaky** [flauc/angular2-notifications#58]
I want to use this library, but I'm getting the following error: `Error: Error: XHR error (404 Not Found) loading http://localhost:8000/angular2-notifications(…)`

It says 404 not found, but when I click on `NotificationsService ` in my IDE then it goes to the declaration.

Also I did followed your example. Here is my commit where you can see that I had followed your example:
https://github.com/superzaky/node-portfolio-zaky/commit/9ff7b4d43d3ebc9c8f2dc94891290c611d150deb

Am I missing something or am I doing something wrong?

**Comment by flauc** [comment]
HI @superzaky, i don't know if this is the issue that is causing the error but for starters try removing `NotificationsService` from the providers array on line 10 of `public/app/components/login/login.component.ts`. 

You don't need to register the provider again in your components the `SimpleNotificationsModule` does that for you on bootstrap.

**Comment by superzaky** [comment]
Hello @flauc that didn't solved unfortunately.

**Comment by flauc** [comment]
I'll have a look at the project over the weekend. Sorry i can't help sooner.

**Comment by ersinpw** [comment]
Same problem here :(

**Comment by oytuntez** [comment]
Could this be related to #25? See replies by @rkralston and @oytuntez.

**Comment by ashajjar** [comment]
I am getting the same error... I am using `0.3.0` with rc5

**Comment by ashajjar** [comment]
hey guys I solved the problem, and it turned out to be system config issue, I will guide you through what I've done step-by-step:

1- Update your `angular-cli-build.js` to look like this:

``` js
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(ts|js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      'angular2-notifications/**/*.+(js|js.map)' // <------------------- this is the line I added
    ]
  });
};

```

2- In your `src/system-config.ts` add `'angular2-notifications': 'vendor/angular2-notifications'` to your `const map:any` constant.
3- In your `src/system-config.ts` in the `const packages:any` constant add the following `key-value` pair:

``` js
const packages: any = {
  'angular2-notifications': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'components.js'
  },
};
```

4- Finally to use the classes of this lib, import it in your `.ts` files as usual.

For me this solved the 404 problem, but now I got another issue that is, the options of the notification, they are not working properly -_-

**Comment by flauc** [comment]
Thank you @ashajjar 👍

**Comment by jseparovic** [comment]
Is anyone able to get this working with angular2-seed project from here https://github.com/mgechev/angular-seed#configuration

I'm getting this error:
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/angular2-notifications.js(…)

**Comment by tomlobato** [comment]
@jseparovic +1

**Comment by shavindraSN** [comment]
For those who still have the issue,  try to map as follows in `system.config.js`. It worked for me.
```js
 map: {
    'angular2-notifications': 'npm:angular2-notifications'
 } 
  ```
  instead of 
  ```js
 map: {
    'angular2-notifications': 'node_modules/angular2-notifications/components.js'
 } 
```
