### ISSUE TITLE
Can't resolve all parameters for NotificationComponent: (NotificationsService, ?)

### ISSUE THREAD

**Issue by IpaliboWhyte** [flauc/angular2-notifications#63]
I don't know exactly what I may have done wrong, but after i managed to get rid of the 404 error by setting this configurations: 

**system-config.ts**
```
/** Map relative paths to URLs. */
var map = {
    'angular2-notifications': 'vendor/angular2-notifications',
    'ng2-file-upload': 'vendor/ng2-file-upload/ng2-file-upload.js',
    'moment': 'vendor/moment/moment.js'
}

/** User packages configuration. */
var packages = {
    'vendor/ng2-file-upload': {
        format: 'cjs',
        defaultExtension: 'js'
    },
    'angular2-notifications': {
      defaultExtension: 'js',
      main: 'components.js',
      format: 'cjs'
    }
}
```

**angular-cli-build.js**

```
vendorNpmFiles: [
      .....
      'angular2-notifications/*.+(js|js.map)',
      'angular2-notifications/lib/*.+(js|js.map)',
      .....
]
```

**app.module.ts**
```
import { SimpleNotificationsModule, NotificationsService } from "angular2-notifications"

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    routing,
    SimpleNotificationsModule
  ],
  declarations: [
    AppComponent
  ],
  providers: [
    NotificationsService,
    appRoutingProviders
  ],
  bootstrap: [
    AppComponent
  ]
})
```

I now get this error on **ng serve**

`zone.js:484 Unhandled Promise rejection: Error: Can't resolve all parameters for NotificationComponent: (NotificationsService, ?).`

my **package.json** includes:

```
    "angular2-notifications": "^0.3.3",
    .....

    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "latest",
```

Not too sure why i have this error, I will really appreciate any feedback! Thanks!

**Comment by flauc** [comment]
Hi @IpaliboWhyte 

I've been getting the same issue on RC6 so I've updated the package to be compatibly with RC6. I think updating to RC6 will solve your problem for sure. 

But i will try to make a RC5 project and recreate the error. I'll let you know what i found. Thanks for the report 👍

**Comment by tscislo** [comment]
Unfortunately I get the same error with this package.json

    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "^0.3.0",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "latest",
    "angular2-notifications": "^0.3.3",

**Comment by tscislo** [comment]
Works for me on RC6 :)
