### ISSUE TITLE
Poor performance due to the change detection

### ISSUE THREAD

**Issue by Chocobozzz** [flauc/angular2-notifications#64]
Each time the `setTimeout` function is called a complete change detection seems to be fired. This could result in a significant FPS decrease if we put the `simple-notifications` component in the root component.

Maybe we could avoid the many calls to `setTimeout` if the `showProgressBar` is set to false?

_angular2-notifications version_: 0.2.6 (I did not update my application to Angular RC6).

Thanks :)

**Comment by flauc** [comment]
Hi @Chocobozzz thanks for the report 👍 

To be honest i haven't really seriously considered performance. 

I'll have a closer look in to this now. Do you know what the best way to measure performance is?

**Comment by Chocobozzz** [comment]
Hi @flauc, thanks :)

I think the best way is the Firefox/ Chromium developer tools (performance/profiles/timeline tabs) where you will see a lot of calls to `setTimeout`/`detectChanges`.

**Comment by flauc** [comment]
Hi @Chocobozzz,

Sorry for the long wait. I've used the `runOutsideOfAngular()` from `NgZone` on all of the `setTimeout()`-s. This prevents zone from doing checks on every tick of the interval, greatly increasing performance. 

Thanks again for bringing this to my attention.

**Comment by Chocobozzz** [comment]
Thanks @flauc!
