### ISSUE TITLE
Ignoring lastOnBottom

### ISSUE THREAD

**Issue by Elitro** [flauc/angular2-notifications#67]
I'm using Angular 2 rc6 and notifications v0.3.6.

I'm calling the error notification, and doing an overwrite.

Setting overwrite lastOnBottom to false does not work, while other overwrite options work.

Setting lastOnBottom false in the options object works though.

**Comment by flauc** [comment]
That's strange, I'll have a look right away. 

Thanks for reporting the issue 👍

**Comment by flauc** [comment]
Hi @Elitro i got some bad news for both of use. It looks like i don't know my own documentation any more. So not all of the options can be overwrite and `lastOnBottom` is one of them, it's just the way the notifications are set up. 

Here is the list of all of the notifications that can be overwriten: 

id
animate
timeOut
showProgressBar
pauseOnHover
clickToClose
maxLength
theClass
icons

It's also in the docs: 

https://github.com/flauc/angular2-notifications/blob/master/docs/toastNotifications.md

**Comment by Elitro** [comment]
Oops, alright i missed that. Cheers!

**Comment by flauc** [comment]
Yup so did i, sorry it doesn't solve your problem.
