### ISSUE TITLE
Cannot find name 'Subject' on compile via angular-cli

### ISSUE THREAD

**Issue by BjornMelgaard** [flauc/angular2-notifications#72]
```
ERROR in [default] /home/bjorn/Documents/angular2-todolist/client/node_modules/angular2-notifications/components.d.ts:102:24 
Cannot find name 'Subject'.
```

**Comment by BjornMelgaard** [comment]
And I also noticed that there massive duplications in components.d.ts

**Comment by flauc** [comment]
Hi @BjornMelgaard thank you for pointing it out. I've switched to auto generating the .d.ts recently and I've never properly tested it. 

I think all of this should be resolved in the fix i just pushed.

**Comment by tabareh** [comment]
I'm till getting this error even though I have the following version in my package.json:
    "angular2-notifications": "^0.3.9",
---------------------------------------------
ERROR in [default] C:\Users\abdollahta\Documents\formbuilder\node_modules\angular2-notifications\components.d.ts:102:24
Cannot find name 'Subject'.

**Comment by flauc** [comment]
Can you try updating to the newest version 0.4.3. Let me know if you still have the error on the new version 👍

**Comment by tabareh** [comment]
Thanks! npm install didn't apparently use the latest version 0.4.3. 
Now it's solved

**Comment by flauc** [comment]
Glad to hear it. Let me know if you have any other issues.
