### ISSUE TITLE
Importing from rxjs/RX causes the entire rxjs library to load in SystemJS

### ISSUE THREAD

**Issue by Cody-Nicholson** [flauc/angular2-notifications#73]
This line will cause SystemJS to import most (if not all) rxjs files (~360 files):
import {Subject} from 'rxjs/Rx';

Since only the Subject class is needed we can change this to:
import {Subject} from 'rxjs/Subject';
which results in about ~60 loaded files

**Comment by flauc** [comment]
Thank you for the observation I'll fix that strait away 👍

**Comment by harpreetjohal** [comment]
Dear Flauc,

I am using angular2-notifications 0.3.1 version in my angular 2 application. Now I have updated the application packages with angular2 final release. However angular2-notifications 0.3.1 still have angular release candidate dependency. Request you if you can let me know if there is any final version released which supports angular2 final release version.

Kind regards,
Harpreet

**Comment by flauc** [comment]
Hi @harpreetjohal,

0.4.0 is running on 2.0.0 it's available through npm. If you just run `npm install angular2-notifications` you should get the newest version.

**Comment by flauc** [comment]
Also, I've just made version 0.4.1 available where the entire rxjs library isn't being imported.

**Comment by harpreetjohal** [comment]
Thank you very much for the quick reply. It works very well.

**Comment by flauc** [comment]
It's my pleasure 👍
