### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Options' of undefined

### ISSUE THREAD

**Issue by bl4stwave** [flauc/angular2-notifications#76]
Hi, 

We are getting the following error message:

`Uncaught TypeError: Cannot read property 'Options' of undefined` relative at the line `exports.Options = $__require('57').Options;` in bundle.js

when trying to start the application. Bundle.js comes from bin/bundler.js --prod.

This is our system.config.js:

```
var map = {
        'rxjs':                       (isPublic)? 'rxjs': 'node_modules/rxjs',
        '@angular':                   (isPublic)? '@angular':'node_modules/@angular',
        'angular2-in-memory-web-api': (isPublic)? 'angular2-in-memory-web-api':'node_modules/angular2-in-memory-web-api',
        'angular2-notifications':     (isPublic)? 'angular2-notifications':'node_modules/angular2-notifications'
    };
```

```
// packages tells the System loader how to load when no filename and/or no extension
var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { defaultExtension: 'js' },
    'angular2-notifications':     { main: 'components.js', defaultExtension: 'js' }
};
```

Please, any suggestions? Are we missing something here?

**Comment by flauc** [comment]
I've been doing some updates it's possible that i messed something up with the definitions. I'll have a look right away.

**Comment by mvar** [comment]
This issue only occurs with the newest version of `systemjs-builder` (`0.15.32`). Works well with older `systemjs-builder`.

**Comment by flauc** [comment]
I simply can't figure out what is causing the problem. Options are used in the exact same way as every other interface in the project, i don't see why it's causing problems and nothing else is.

**Comment by flauc** [comment]
This is no longer a problem in the latest release.
