### ISSUE TITLE
theClass option is ignored in version 0.4.2

### ISSUE THREAD

**Issue by ragnarruutel** [flauc/angular2-notifications#77]
While loading user provided options hasOwnProperty in attachChanges method
https://github.com/flauc/angular2-notifications/blob/master/src/simple-notifications.component.ts#L189
returns false for 'theClass' because property is not initialized 
https://github.com/flauc/angular2-notifications/blob/master/src/simple-notifications.component.ts#L78

private theClass: string = '';

**Comment by flauc** [comment]
Thank you for posting this 👍 

I've published a new version 0.4.3 with the fix.
