### ISSUE TITLE
is permission granted already?

### ISSUE THREAD

**Issue by iBasit** [flauc/angular2-notifications#79]
How to check if permission is already granted or not? 

I want to display message, if its not already granted. 

I have seent status "granted", "deny" and "default".. can default means not granted yet?

**Comment by flauc** [comment]
Hi @iBasit 

This is what each permission value means 
- granted: The user has explicitly granted permission for the current origin to display system notifications.
- denied: The user has explicitly denied permission for the current origin to display system notifications.
- default: The user decision is unknown; in this case the application will act as if permission was denied.

The Notification object has the permission property on it so you can check what the current value is simply like this: 

```js
console.log(Notification.permission)
```
This is the Notification API object not the library service. You can also check the value of the permission using the library like this: 

```js
console.log(this.pushNotificationsService.permission)
```
However the permission property in the service will only have the valid value if you have called the `requestPermission()` method at least once. 

So i would recommend using the `Notification` object directly.

**Comment by iBasit** [comment]
You can also add, if isSupported or not by browser, it will be good in some conditions on the app.

```
isSupported = (function () {
            var isSupported = false;
            /*
             * Use try {} catch() {} because the check for IE may throws an exception
             * if the code is run on browser that is not Safar/Chrome/IE or
             * Firefox with html5notifications plugin.
             *
             * Also, we canNOT detect if msIsSiteMode method exists, as it is
             * a method of host object. In IE check for existing method of host
             * object returns undefined. So, we try to run it - if it runs
             * successfully - then it is IE9+, if not - an exceptions is thrown.
             */
            try {
                isSupported = !!(/* Safari, Chrome */win.Notification || /* Chrome & ff-html5notifications plugin */win.webkitNotifications || /* Firefox Mobile */navigator.mozNotification || /* IE9+ */(win.external && win.external.msIsSiteMode() !== undefined));
            } catch (e) {}
            return isSupported;
        }()),
```

**Comment by flauc** [comment]
That's a great idea. I'll have it added right away. Thank you 👍
