### ISSUE TITLE
possibility to remove a specific notification's popup

### ISSUE THREAD

**Issue by yahyaKacem** [flauc/angular2-notifications#8]
Hi, thanks for your efforts.
It would be great if I can remove a specific popup after it's displayed, like:

```
successId = this._notificationsService.success(
    title: 'example', 
    content:'example', 
    override: {
        timeOut: 5000,
        showProgressBar: true,
        pauseOnHover: false,
        clickToClose: false,
        maxLength: 10
    }
);
// do some stuff
// then when I need to close it:
this._notificationsService.close(successID);
```

**Comment by flauc** [comment]
Hi, that's a great idea. I'll try to implement it as soon as possible.

**Comment by flauc** [comment]
Hi again, 

I've renamed the 'removeAll' method on the notificationsService to just 'remove'. It accepts an optional id as input, if no id was passed then all the notifications get deleted. 

So what you need to do is get hold of the notifications id. You do that by subscribing to the 'onCreate' event. Then when a notification is created the notification object gets emitted which contains the id of the notification. Then you just pass the id to the remove method. 

It might sound complicated but it really isn't, here is some example code: 

HTML
```html
<simple-notifications [options]="options" (onCreate)="onCreate($event)"></simple-notifications>
<form (ngSubmit)="clean()">
    /* copy the id of the created notification from the console */
    <input type="text" [(ngModel)]="deleteId">
    <button type="submit">Delete</button>
</form>
``` 
Component
```js

public deleteId: string;

onCreate(event) {
   // The entire notification get's logged as well as the id
   console.log(event);
}

clean() {
    // If no id gets passed then all of the notifications get deleted
    this._service.remove(this.deleteId);
}
```    

I'll update the readme and the sample page tomorrow, until then you can check out the example folder in the repo. 

Hope this works for you, and thank you for the advice.
