### ISSUE TITLE
Title overlaps with icon [CSS]

### ISSUE THREAD

**Issue by seansean11** [flauc/angular2-notifications#83]
The title overlaps with icon when it doesn't wrap early.

<img width="323" alt="screen shot 2016-10-08 at 9 51 41 pm" src="https://cloud.githubusercontent.com/assets/2547722/19217829/b2a87e36-8da2-11e6-9bad-c8c4f23e1630.png">

**Comment by flauc** [comment]
I've just merged your pull request I'll publish to npm later today. Thanks again 👍
