### ISSUE TITLE
Click event on toast notifications

### ISSUE THREAD

**Issue by sergiocosus** [flauc/angular2-notifications#87]
Is there a way to listen the click event on Toast Notifications?

**Comment by flauc** [comment]
Hi @sergiocosus,

There isn't at the moment no. I can't believe i never thought to implement that. I'll have that implemented.  👍

**Comment by sergiocosus** [comment]
Hi! @flauc 
I just have made a pull request to manage that, #88 

How do you see this implementation?

By the way, thanks for this amazing library!

**Comment by flauc** [comment]
This has been implemented.
