### ISSUE TITLE
Misbehaving notifications

### ISSUE THREAD

**Issue by miket969** [flauc/angular2-notifications#9]
Hi,

I am trying to implement your package in the [angular 2 seed](https://github.com/mgechev/angular2-seed) project and firing the `this._service.success('A notification', 'Something you should know...');` code. I am noticing that the notifications are misbehaving: 
-  the notifications do not disappear when the timeout elapses
-  the close on click does not work
-  new notifications keep getting triggered when the timeout of the last one finishes or I click on an existing one

I have tried replicating the cod in your example as closely as possible. The only difference is that I have not needed to map the libray. The seed is using System.JS but the configuration is in the config.ts file.
I have added a link to a project that reproduces the problem. Any insights would be greatly helpful.

https://www.dropbox.com/s/biui2ngo7xt3cex/notification-test.zip?dl=0

**Comment by flauc** [comment]
I've added some new functionality the day before yesterday and it looks like i broke something in the process. Sorry for the inconvenience, i'm already trying to figure out what's wrong.

**Comment by flauc** [comment]
Hey, 

The bugs have all been fixed, just run npm install again and every thing should be working just fine. Let me know how it goes.

**Comment by miket969** [comment]
It works fine! Thank you :)
