### ISSUE TITLE
upgraded from Angular RC.5 to Angular 2.1.1 release

### ISSUE THREAD

**Issue by codecentre** [flauc/angular2-notifications#90]
getting this issue with same code base: Error: (SystemJS) Can't resolve all parameters for NotificationComponent: (NotificationsService, ?).(…)

what is wrong?

i think it has something to do with the SanitizationService in platform-browser package

**Comment by flauc** [comment]
Hi @codecentre, 

How are you importing the SimpleNotificationsModule?

**Comment by codecentre** [comment]
I fixed it. I had to update the platform browser module and upgrade from 0.3 to your 0.4.4 version and it all works.


Get Outlook for Android






On Fri, Oct 28, 2016 at 7:28 PM -0400, "Filip Lauc" <notifications@github.com> wrote:





Hi @codecentre,

How are you importing the SimpleNotificationsModule?

**Comment by flauc** [comment]
Great you got it working 👍
