### ISSUE TITLE
PhantomJS error from icon.ts

### ISSUE THREAD

**Issue by Simon-Briggs** [flauc/angular2-notifications#91]
Hey, 

I've just updated from 0.4.4 to 0.4.41 and have started getting an error when running my Karma Unit tests on PhantomJS. I see this icon.ts file hasn't been updated between 0.4.4 and 0.4.41, so was wondering if there's changes in other files that use icon.ts?

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Invalid character: '`'
  at webpack:///~/angular2-notifications/src/icons.ts:9:2 <- test-config/spec-bundle.js:57571
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Invalid character: '`'
  at webpack:///~/angular2-notifications/src/icons.ts:9:2 <- test-config/spec-bundle.js:57571
```

My tests still run fine on Chrome so it seems like some ES5/ES6 issue.

**Comment by flauc** [comment]
I've been working on AoT compilation. I might have messed something up ( still trying to resolve the AoT issue #82). 

Could you lock the version to 0.4.4 for now. I'll let you know as soon as i get this working. 

Also , thank you for pointing this out 👍

**Comment by flauc** [comment]
Hi @Simon-Briggs 

Did you maybe have a chance trying your build with 0.4.46?

**Comment by Simon-Briggs** [comment]
Hi @flauc 

I don't get this error any more with 0.4.46.

Thank you!!

**Comment by flauc** [comment]
Grate to hear, closing up the issue 👍
