### ISSUE TITLE
Service should assign permission in constructor

### ISSUE THREAD

**Issue by MennoVS** [flauc/angular2-notifications#92]
At this moment the push-notifications.service assigns Notification.permission to this.permission in the create method. This makes it impossible for the user to check the permission (through the service API) before calling create, thus the safe creation of a notification is not possible.

I suggest moving this assignment to the constructor of the service, enabling the user to safely create a notification.

```
export class PushNotificationsService {
    permission: Permission;

    constructor() {
        this.permission  = this.isSupported() ? Notification.permission : 'denied';
    }

    ...
}
```

**Comment by flauc** [comment]
You're right 👍 

Are you interested in posting a PR, I'm not going to be on the computer all day, so that would be really helpful?

**Comment by MennoVS** [comment]
I posted a PR to fix this #93

**Comment by flauc** [comment]
I'll push a new release as soon as i get home.

**Comment by MennoVS** [comment]
Great, thanks!
