### ISSUE TITLE
Erro from UgilfyJs

### ISSUE THREAD

**Issue by thewizarodofoz** [flauc/angular2-notifications#95]
In my Angular2 project with Webpack, I'm trying to use this package, but getting this error from Webpack:

> ERROR in app.js from UglifyJs
> SyntaxError: Unexpected token: name (SimpleNotificationsModule) [./~/angular2-notifications/lib/simple-notifications.module.js:8,0]

**Comment by flauc** [comment]
Hi @thewizarodofoz ,

So this error only occurs when uglify-ed? 
What version of the library are you using?

**Comment by thewizarodofoz** [comment]
Yes, if I remove the UgilfyJsPlugin from my webpack config file, it works.
angular2-notifications version is 0.4.41.

**Comment by flauc** [comment]
Can you try updating to 0.4.45 and see if the issue persists? 
I've been working on AoT compilation and I'm not sure if everything is setup correctly.

**Comment by thewizarodofoz** [comment]
Working great now! Thanks a million.
