### ISSUE TITLE
PushNotification close() does not work

### ISSUE THREAD

**Issue by MennoVS** [flauc/angular2-notifications#96]
The close function on the Notification class was overwritten/wrapped to call obs.complete().
However I cannot get the notification to close, it doesn't throw any errors either.
If I remove that code, the notification closes and Notification.onclose is called, in turn calling obs.complete().

Current implementation:
```
n.onclose = () => obs.complete();
n.close = () => {
    n.close.bind(n);
    obs.complete();
};
```

Suggested fix:
```
n.onclose = () => obs.complete();
// n.close = () => {
//     n.close.bind(n);
//     obs.complete();
// };
```

If anyone has a better idea please let me know, else I'll make a PR.

**Comment by flauc** [comment]
Hi again @MennoVS,

Funny i thought i tested it, anyway, go ahead and make the PR, I'll look in to it later. 

Thanks again for all your help 👍

**Comment by r-vijay-r** [comment]
please give me an example to close pushNotification. also it will be great if you show how to put icon in push notification

**Comment by MennoVS** [comment]
Hi @r-vijay-r ,

You would basically use the standard [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification) through the PushNotificationsService.

```
private _notification;

// inject the PushNotificationsService
constructor(private _pushNotificationsService: PushNotificationsService) {

    // create a notification and store a reference
    this._notification = this._pushNotificationService.create('Title');

    // later, when you wish to close it, call close() on the reference
    this._notification.close();
}
```

Unfortunately I've not yet been able to find/use the Notification type, but this should work.
