### ISSUE TITLE
please provide better example in push notification

### ISSUE THREAD

**Issue by r-vijay-r** [flauc/angular2-notifications#98]
please give me an example to close pushNotification with a timeout of say 5000ms. Also it will be great if you show how to put icon in push notification since i cant find in documentation how to add icon to push notification.

**Comment by flauc** [comment]
Hi @r-vijay-r,

Sorry for the slow response was really short on time lately. 

Anyway here is an example of closing the notification: #96 
You would just wrap the `this._notification.close();` in a `setTimeout(() => this._notification.close(), 5000)`

You can also fine how to use icons on that issue, any options supported by the desktop `Notifications API` can be found here: 

https://developer.mozilla.org/en/docs/Web/API/notification

**Comment by sjmorgan** [comment]
Hi, I have <simple-notifications> working but not the push notifications.
Here's what I have ... am I missing something?

I did notice that Options isn't exported from 'angular2-notifications', if that's relevant.

Thanks
-Simon

=============MODULE===========================================
import { PushNotificationsModule, PushNotificationsService, SimpleNotificationsModule, SimpleNotificationsComponent} from 'angular2-notifications';
...
@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        MaterialModule.forRoot(),
        SimpleNotificationsModule,
        PushNotificationsModule,
        RouterModule.forRoot(routes, { useHash: true }),
        FlexLayoutModule.forRoot(),
    ],
==============COMPONENT============================================
import { PushNotificationsService, SimpleNotificationsComponent, NotificationsService } from 'angular2-notifications';
...
export class AppComponent implements OnInit {
    constructor( private _pushNotifications: PushNotificationsService) { }
    ngOnInit() {
    }
    getPermission() {
        this._pushNotifications.requestPermission();
    }
    create() {
        this._pushNotifications.create('Test', {body: 'testing...'}).subscribe(
            res => console.log(res),
            err => console.log(err)
        )
    }   
===============HTML==========================================
 ....  
   <button (click)="getPermission()">Get push permission</button>
    <button (click)="create()">Send Push Notification</button>
....
=============================================================

**Comment by wzfjesun** [comment]
you can do like this:

this._push.create('Test', {body: 'something'}).subscribe(
    res => setTimeout(() => res.notification.close(), 2000),    
    err => console.log(err)
 )

**Comment by flauc** [comment]
Please refer to this repo for more info: 

https://github.com/flauc/ng-push
